//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Payload for the &#x60;account-link-initiated&#x60; callback method. Sent by CodaPay when the merchant begins the account-link flow, before the full account-link callback arrives.
    /// </summary>
    [Preserve]
    [DataContract(Name = "account-link-initiated-request")]
    internal class AccountLinkInitiatedRequest
    {
        /// <summary>
        /// Payload for the &#x60;account-link-initiated&#x60; callback method. Sent by CodaPay when the merchant begins the account-link flow, before the full account-link callback arrives.
        /// </summary>
        /// <param name="method">Callback method type</param>
        /// <param name="linkId">Link ID previously generated by the signup-url endpoint</param>
        /// <param name="settlementId">CodaPay settlement identifier</param>
        [Preserve]
        public AccountLinkInitiatedRequest(MethodOptions method, string linkId, int settlementId)
        {
            Method = method;
            LinkId = linkId;
            SettlementId = settlementId;
        }

        /// <summary>
        /// Callback method type
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "method", IsRequired = true, EmitDefaultValue = true)]
        public MethodOptions Method{ get; }
        
        /// <summary>
        /// Link ID previously generated by the signup-url endpoint
        /// </summary>
        [Preserve]
        [DataMember(Name = "linkId", IsRequired = true, EmitDefaultValue = true)]
        public string LinkId{ get; }
        
        /// <summary>
        /// CodaPay settlement identifier
        /// </summary>
        [Preserve]
        [DataMember(Name = "settlementId", IsRequired = true, EmitDefaultValue = true)]
        public int SettlementId{ get; }
    
        /// <summary>
        /// Callback method type
        /// </summary>
        /// <value>Callback method type</value>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MethodOptions
        {
            /// <summary>
            /// Enum AccountLinkInitiated for value: account-link-initiated
            /// </summary>
            [EnumMember(Value = "account-link-initiated")]
            AccountLinkInitiated = 1
        }

        /// <summary>
        /// Formats a AccountLinkInitiatedRequest into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "method," + Method + ",";
            if (LinkId != null)
            {
                serializedModel += "linkId," + LinkId + ",";
            }
            serializedModel += "settlementId," + SettlementId.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a AccountLinkInitiatedRequest as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var methodStringValue = Method.ToString();
            dictionary.Add("method", methodStringValue);
            
            if (LinkId != null)
            {
                var linkIdStringValue = LinkId.ToString();
                dictionary.Add("linkId", linkIdStringValue);
            }
            
            var settlementIdStringValue = SettlementId.ToString();
            dictionary.Add("settlementId", settlementIdStringValue);
            
            return dictionary;
        }
    }
}
