//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Device information provided by the IAP SDK for analytics enrichment.
    /// </summary>
    [Preserve]
    [DataContract(Name = "device-info")]
    internal class DeviceInfo
    {
        /// <summary>
        /// Device information provided by the IAP SDK for analytics enrichment.
        /// </summary>
        /// <param name="language">System language of the device (BCP 47 format).</param>
        /// <param name="platform">Platform the game is running on (e.g. &#x60;ios&#x60;, &#x60;android&#x60;).</param>
        /// <param name="localeList">Ordered list of locales configured on the device.</param>
        /// <param name="deviceModel">Device model identifier.</param>
        /// <param name="systemBootTime">Unix timestamp (seconds) of the last system boot.</param>
        /// <param name="osVersion">Operating system version.</param>
        /// <param name="appBundleId">Application bundle identifier.</param>
        /// <param name="totalSpace">Total device storage in bytes.</param>
        [Preserve]
        public DeviceInfo(string language = default, string platform = default, List<string> localeList = default, string deviceModel = default, long systemBootTime = default, string osVersion = default, string appBundleId = default, long totalSpace = default)
        {
            Language = language;
            Platform = platform;
            LocaleList = localeList;
            DeviceModel = deviceModel;
            SystemBootTime = systemBootTime;
            OsVersion = osVersion;
            AppBundleId = appBundleId;
            TotalSpace = totalSpace;
        }

        /// <summary>
        /// System language of the device (BCP 47 format).
        /// </summary>
        [Preserve]
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language{ get; }
        
        /// <summary>
        /// Platform the game is running on (e.g. &#x60;ios&#x60;, &#x60;android&#x60;).
        /// </summary>
        [Preserve]
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        public string Platform{ get; }
        
        /// <summary>
        /// Ordered list of locales configured on the device.
        /// </summary>
        [Preserve]
        [DataMember(Name = "localeList", EmitDefaultValue = false)]
        public List<string> LocaleList{ get; }
        
        /// <summary>
        /// Device model identifier.
        /// </summary>
        [Preserve]
        [DataMember(Name = "deviceModel", EmitDefaultValue = false)]
        public string DeviceModel{ get; }
        
        /// <summary>
        /// Unix timestamp (seconds) of the last system boot.
        /// </summary>
        [Preserve]
        [DataMember(Name = "systemBootTime", EmitDefaultValue = false)]
        public long SystemBootTime{ get; }
        
        /// <summary>
        /// Operating system version.
        /// </summary>
        [Preserve]
        [DataMember(Name = "osVersion", EmitDefaultValue = false)]
        public string OsVersion{ get; }
        
        /// <summary>
        /// Application bundle identifier.
        /// </summary>
        [Preserve]
        [DataMember(Name = "appBundleId", EmitDefaultValue = false)]
        public string AppBundleId{ get; }
        
        /// <summary>
        /// Total device storage in bytes.
        /// </summary>
        [Preserve]
        [DataMember(Name = "totalSpace", EmitDefaultValue = false)]
        public long TotalSpace{ get; }
    
        /// <summary>
        /// Formats a DeviceInfo into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Language != null)
            {
                serializedModel += "language," + Language + ",";
            }
            if (Platform != null)
            {
                serializedModel += "platform," + Platform + ",";
            }
            if (LocaleList != null)
            {
                serializedModel += "localeList," + LocaleList.ToString() + ",";
            }
            if (DeviceModel != null)
            {
                serializedModel += "deviceModel," + DeviceModel + ",";
            }
            serializedModel += "systemBootTime," + SystemBootTime.ToString() + ",";
            if (OsVersion != null)
            {
                serializedModel += "osVersion," + OsVersion + ",";
            }
            if (AppBundleId != null)
            {
                serializedModel += "appBundleId," + AppBundleId + ",";
            }
            serializedModel += "totalSpace," + TotalSpace.ToString();
            return serializedModel;
        }

        /// <summary>
        /// Returns a DeviceInfo as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Language != null)
            {
                var languageStringValue = Language.ToString();
                dictionary.Add("language", languageStringValue);
            }
            
            if (Platform != null)
            {
                var platformStringValue = Platform.ToString();
                dictionary.Add("platform", platformStringValue);
            }
            
            if (LocaleList != null)
            {
                var localeListStringValue = LocaleList.ToString();
                dictionary.Add("localeList", localeListStringValue);
            }
            
            if (DeviceModel != null)
            {
                var deviceModelStringValue = DeviceModel.ToString();
                dictionary.Add("deviceModel", deviceModelStringValue);
            }
            
            var systemBootTimeStringValue = SystemBootTime.ToString();
            dictionary.Add("systemBootTime", systemBootTimeStringValue);
            
            if (OsVersion != null)
            {
                var osVersionStringValue = OsVersion.ToString();
                dictionary.Add("osVersion", osVersionStringValue);
            }
            
            if (AppBundleId != null)
            {
                var appBundleIdStringValue = AppBundleId.ToString();
                dictionary.Add("appBundleId", appBundleIdStringValue);
            }
            
            var totalSpaceStringValue = TotalSpace.ToString();
            dictionary.Add("totalSpace", totalSpaceStringValue);
            
            return dictionary;
        }
    }
}
