//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// GoogleTransactionRequest model
    /// </summary>
    [Preserve]
    [DataContract(Name = "google-transaction-request")]
    internal class GoogleTransactionRequest
    {
        /// <summary>
        /// Creates an instance of GoogleTransactionRequest.
        /// </summary>
        /// <param name="receipt">Google receipt from the IAP SDK.</param>
        [Preserve]
        public GoogleTransactionRequest(string receipt)
        {
            Receipt = receipt;
        }

        /// <summary>
        /// Google receipt from the IAP SDK.
        /// </summary>
        [Preserve]
        [DataMember(Name = "receipt", IsRequired = true, EmitDefaultValue = true)]
        public string Receipt{ get; }
    
        /// <summary>
        /// Formats a GoogleTransactionRequest into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Receipt != null)
            {
                serializedModel += "receipt," + Receipt;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a GoogleTransactionRequest as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Receipt != null)
            {
                var receiptStringValue = Receipt.ToString();
                dictionary.Add("receipt", receiptStringValue);
            }
            
            return dictionary;
        }
    }
}
