//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// LinkOutSessionRegisterRequest model
    /// </summary>
    [Preserve]
    [DataContract(Name = "link-out-session-register-request")]
    internal class LinkOutSessionRegisterRequest
    {
        /// <summary>
        /// Creates an instance of LinkOutSessionRegisterRequest.
        /// </summary>
        /// <param name="identity">identity param</param>
        /// <param name="deviceInfo">deviceInfo param</param>
        [Preserve]
        public LinkOutSessionRegisterRequest(PlayerIdentity identity, DeviceInfo deviceInfo = default)
        {
            Identity = identity;
            DeviceInfo = deviceInfo;
        }

        /// <summary>
        /// Parameter identity of LinkOutSessionRegisterRequest
        /// </summary>
        [Preserve]
        [DataMember(Name = "identity", IsRequired = true, EmitDefaultValue = true)]
        public PlayerIdentity Identity{ get; }
        
        /// <summary>
        /// Parameter deviceInfo of LinkOutSessionRegisterRequest
        /// </summary>
        [Preserve]
        [DataMember(Name = "deviceInfo", EmitDefaultValue = false)]
        public DeviceInfo DeviceInfo{ get; }
    
        /// <summary>
        /// Formats a LinkOutSessionRegisterRequest into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Identity != null)
            {
                serializedModel += "identity," + Identity.ToString() + ",";
            }
            if (DeviceInfo != null)
            {
                serializedModel += "deviceInfo," + DeviceInfo.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a LinkOutSessionRegisterRequest as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            return dictionary;
        }
    }
}
