//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// LinkOutSessionRegisterResponse model
    /// </summary>
    [Preserve]
    [DataContract(Name = "link-out-session-register-response")]
    internal class LinkOutSessionRegisterResponse
    {
        /// <summary>
        /// Creates an instance of LinkOutSessionRegisterResponse.
        /// </summary>
        /// <param name="linkOutSessionId">Backend-minted opaque key the webshop relays at order-create.</param>
        [Preserve]
        public LinkOutSessionRegisterResponse(System.Guid linkOutSessionId = default)
        {
            LinkOutSessionId = linkOutSessionId;
        }

        /// <summary>
        /// Backend-minted opaque key the webshop relays at order-create.
        /// </summary>
        [Preserve]
        [DataMember(Name = "linkOutSessionId", EmitDefaultValue = false)]
        public System.Guid LinkOutSessionId{ get; }
    
        /// <summary>
        /// Formats a LinkOutSessionRegisterResponse into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (LinkOutSessionId != null)
            {
                serializedModel += "linkOutSessionId," + LinkOutSessionId;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a LinkOutSessionRegisterResponse as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (LinkOutSessionId != null)
            {
                var linkOutSessionIdStringValue = LinkOutSessionId.ToString();
                dictionary.Add("linkOutSessionId", linkOutSessionIdStringValue);
            }
            
            return dictionary;
        }
    }
}
