//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Response returned from confirm/cancel mock checkout actions, containing the deep link the client should follow back to the game.
    /// </summary>
    [Preserve]
    [DataContract(Name = "mock-checkout-action-response")]
    internal class MockCheckoutActionResponse
    {
        /// <summary>
        /// Response returned from confirm/cancel mock checkout actions, containing the deep link the client should follow back to the game.
        /// </summary>
        /// <param name="redirectUrl">Deep link URL the client should redirect to.</param>
        [Preserve]
        public MockCheckoutActionResponse(string redirectUrl)
        {
            RedirectUrl = redirectUrl;
        }

        /// <summary>
        /// Deep link URL the client should redirect to.
        /// </summary>
        [Preserve]
        [DataMember(Name = "redirectUrl", IsRequired = true, EmitDefaultValue = true)]
        public string RedirectUrl{ get; }
    
        /// <summary>
        /// Formats a MockCheckoutActionResponse into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (RedirectUrl != null)
            {
                serializedModel += "redirectUrl," + RedirectUrl;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a MockCheckoutActionResponse as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (RedirectUrl != null)
            {
                var redirectUrlStringValue = RedirectUrl.ToString();
                dictionary.Add("redirectUrl", redirectUrlStringValue);
            }
            
            return dictionary;
        }
    }
}
