//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// MockCheckoutOrderResponseLineItemsInner model
    /// </summary>
    [Preserve]
    [DataContract(Name = "mock_checkout_order_response_lineItems_inner")]
    internal class MockCheckoutOrderResponseLineItemsInner
    {
        /// <summary>
        /// Creates an instance of MockCheckoutOrderResponseLineItemsInner.
        /// </summary>
        /// <param name="sku">Product SKU.</param>
        /// <param name="productType">Type of the product.</param>
        /// <param name="price">Price amount in micros (1,000,000 micros &#x3D; 1 unit of currency)</param>
        /// <param name="currency">ISO 4217 currency code</param>
        [Preserve]
        public MockCheckoutOrderResponseLineItemsInner(string sku, string productType, long price, string currency)
        {
            Sku = sku;
            ProductType = productType;
            Price = price;
            Currency = currency;
        }

        /// <summary>
        /// Product SKU.
        /// </summary>
        [Preserve]
        [DataMember(Name = "sku", IsRequired = true, EmitDefaultValue = true)]
        public string Sku{ get; }
        
        /// <summary>
        /// Type of the product.
        /// </summary>
        [Preserve]
        [DataMember(Name = "productType", IsRequired = true, EmitDefaultValue = true)]
        public string ProductType{ get; }
        
        /// <summary>
        /// Price amount in micros (1,000,000 micros &#x3D; 1 unit of currency)
        /// </summary>
        [Preserve]
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public long Price{ get; }
        
        /// <summary>
        /// ISO 4217 currency code
        /// </summary>
        [Preserve]
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency{ get; }
    
        /// <summary>
        /// Formats a MockCheckoutOrderResponseLineItemsInner into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Sku != null)
            {
                serializedModel += "sku," + Sku + ",";
            }
            if (ProductType != null)
            {
                serializedModel += "productType," + ProductType + ",";
            }
            serializedModel += "price," + Price.ToString() + ",";
            if (Currency != null)
            {
                serializedModel += "currency," + Currency;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a MockCheckoutOrderResponseLineItemsInner as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Sku != null)
            {
                var skuStringValue = Sku.ToString();
                dictionary.Add("sku", skuStringValue);
            }
            
            if (ProductType != null)
            {
                var productTypeStringValue = ProductType.ToString();
                dictionary.Add("productType", productTypeStringValue);
            }
            
            var priceStringValue = Price.ToString();
            dictionary.Add("price", priceStringValue);
            
            if (Currency != null)
            {
                var currencyStringValue = Currency.ToString();
                dictionary.Add("currency", currencyStringValue);
            }
            
            return dictionary;
        }
    }
}
