//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Optional. Per-order override of the project&#39;s globally configured redirect URLs. When provided, &#x60;successUrl&#x60; is required and the object fully replaces the global config for this order; when omitted, the global config is used.
    /// </summary>
    [Preserve]
    [DataContract(Name = "order_request_redirectUrls")]
    internal class OrderRequestRedirectUrls
    {
        /// <summary>
        /// Optional. Per-order override of the project&#39;s globally configured redirect URLs. When provided, &#x60;successUrl&#x60; is required and the object fully replaces the global config for this order; when omitted, the global config is used.
        /// </summary>
        /// <param name="successUrl">Redirect target after a successful checkout. Must be an absolute https URL on the project&#39;s webshop host (e.g. &#x60;shop.unity.com&#x60;); other hosts are rejected.</param>
        /// <param name="cancelUrl">Redirect target when the player cancels or abandons checkout. Applies to Stripe checkout only; ignored by providers without a cancel step. Must be on the project&#39;s webshop host.</param>
        [Preserve]
        public OrderRequestRedirectUrls(string successUrl, string cancelUrl = default)
        {
            SuccessUrl = successUrl;
            CancelUrl = cancelUrl;
        }

        /// <summary>
        /// Redirect target after a successful checkout. Must be an absolute https URL on the project&#39;s webshop host (e.g. &#x60;shop.unity.com&#x60;); other hosts are rejected.
        /// </summary>
        [Preserve]
        [DataMember(Name = "successUrl", IsRequired = true, EmitDefaultValue = true)]
        public string SuccessUrl{ get; }
        
        /// <summary>
        /// Redirect target when the player cancels or abandons checkout. Applies to Stripe checkout only; ignored by providers without a cancel step. Must be on the project&#39;s webshop host.
        /// </summary>
        [Preserve]
        [DataMember(Name = "cancelUrl", EmitDefaultValue = false)]
        public string CancelUrl{ get; }
    
        /// <summary>
        /// Formats a OrderRequestRedirectUrls into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (SuccessUrl != null)
            {
                serializedModel += "successUrl," + SuccessUrl + ",";
            }
            if (CancelUrl != null)
            {
                serializedModel += "cancelUrl," + CancelUrl;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a OrderRequestRedirectUrls as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (SuccessUrl != null)
            {
                var successUrlStringValue = SuccessUrl.ToString();
                dictionary.Add("successUrl", successUrlStringValue);
            }
            
            if (CancelUrl != null)
            {
                var cancelUrlStringValue = CancelUrl.ToString();
                dictionary.Add("cancelUrl", cancelUrlStringValue);
            }
            
            return dictionary;
        }
    }
}
