//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Request body for creating an order
    /// </summary>
    [Preserve]
    [DataContract(Name = "order-request")]
    internal class OrderRequest
    {
        /// <summary>
        /// Request body for creating an order
        /// </summary>
        /// <param name="player">player param</param>
        /// <param name="currency">Currency code in ISO 4217 format. Required. If the requested currency is not configured for the product, the order falls back to USD pricing. If neither the requested currency nor USD is configured, the order is rejected.</param>
        /// <param name="skus">Array of product SKUs. Currently must contain exactly one SKU. Deprecated in favour of &#x60;catalogListingIds&#x60;; still supported during the transition period. Provide either &#x60;skus&#x60; or &#x60;catalogListingIds&#x60;.</param>
        /// <param name="catalogListingIds">Array of catalog listing identifiers to purchase. Currently must contain exactly one identifier. Replaces &#x60;skus&#x60; because SKUs are not guaranteed to be unique. Each identifier is the Live Content config path of the catalog listing and typically looks like a relative file path. Provide either &#x60;skus&#x60; or &#x60;catalogListingIds&#x60;.</param>
        /// <param name="country">Country of purchase in ISO 3166-1 alpha-2 format. Used by payment providers that require a country-of-purchase signal (currently Coda Pay only); ignored by others. When omitted, the country is derived from the player&#39;s locale as a temporary backward-compatibility fallback for older SDK versions.</param>
        /// <param name="paymentProvider">Optional. Specify payment provider instead of using the default one configured for this project environment.</param>
        /// <param name="externalTransactionTokens">Optional external-link transaction tokens, used by developers to self-report the transaction to Apple/Google. Stored with the order and surfaced in order webhooks; not returned in the order response. Up to two tokens may be supplied because a single Apple external purchase can yield two distinct token types depending on the region — for example an &#x60;acquisition&#x60; token and a &#x60;linkOut&#x60; token.</param>
        /// <param name="deviceInfo">deviceInfo param</param>
        [Preserve]
        public OrderRequest(Player player, string currency, List<string> skus = default, List<string> catalogListingIds = default, string country = default, string paymentProvider = default, List<OrderRequestExternalTransactionTokensInner> externalTransactionTokens = default, DeviceInfo deviceInfo = default)
        {
            Player = player;
            Skus = skus;
            CatalogListingIds = catalogListingIds;
            Currency = currency;
            Country = country;
            PaymentProvider = paymentProvider;
            ExternalTransactionTokens = externalTransactionTokens;
            DeviceInfo = deviceInfo;
        }

        /// <summary>
        /// Parameter player of OrderRequest
        /// </summary>
        [Preserve]
        [DataMember(Name = "player", IsRequired = true, EmitDefaultValue = true)]
        public Player Player{ get; }
        
        /// <summary>
        /// Array of product SKUs. Currently must contain exactly one SKU. Deprecated in favour of &#x60;catalogListingIds&#x60;; still supported during the transition period. Provide either &#x60;skus&#x60; or &#x60;catalogListingIds&#x60;.
        /// </summary>
        [Preserve]
        [DataMember(Name = "skus", EmitDefaultValue = false)]
        public List<string> Skus{ get; }
        
        /// <summary>
        /// Array of catalog listing identifiers to purchase. Currently must contain exactly one identifier. Replaces &#x60;skus&#x60; because SKUs are not guaranteed to be unique. Each identifier is the Live Content config path of the catalog listing and typically looks like a relative file path. Provide either &#x60;skus&#x60; or &#x60;catalogListingIds&#x60;.
        /// </summary>
        [Preserve]
        [DataMember(Name = "catalogListingIds", EmitDefaultValue = false)]
        public List<string> CatalogListingIds{ get; }
        
        /// <summary>
        /// Currency code in ISO 4217 format. Required. If the requested currency is not configured for the product, the order falls back to USD pricing. If neither the requested currency nor USD is configured, the order is rejected.
        /// </summary>
        [Preserve]
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency{ get; }
        
        /// <summary>
        /// Country of purchase in ISO 3166-1 alpha-2 format. Used by payment providers that require a country-of-purchase signal (currently Coda Pay only); ignored by others. When omitted, the country is derived from the player&#39;s locale as a temporary backward-compatibility fallback for older SDK versions.
        /// </summary>
        [Preserve]
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country{ get; }
        
        /// <summary>
        /// Optional. Specify payment provider instead of using the default one configured for this project environment.
        /// </summary>
        [Preserve]
        [DataMember(Name = "paymentProvider", EmitDefaultValue = false)]
        public string PaymentProvider{ get; }
        
        /// <summary>
        /// Optional external-link transaction tokens, used by developers to self-report the transaction to Apple/Google. Stored with the order and surfaced in order webhooks; not returned in the order response. Up to two tokens may be supplied because a single Apple external purchase can yield two distinct token types depending on the region — for example an &#x60;acquisition&#x60; token and a &#x60;linkOut&#x60; token.
        /// </summary>
        [Preserve]
        [DataMember(Name = "externalTransactionTokens", EmitDefaultValue = false)]
        public List<OrderRequestExternalTransactionTokensInner> ExternalTransactionTokens{ get; }
        
        /// <summary>
        /// Parameter deviceInfo of OrderRequest
        /// </summary>
        [Preserve]
        [DataMember(Name = "deviceInfo", EmitDefaultValue = false)]
        public DeviceInfo DeviceInfo{ get; }
    
        /// <summary>
        /// Formats a OrderRequest into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Player != null)
            {
                serializedModel += "player," + Player.ToString() + ",";
            }
            if (Skus != null)
            {
                serializedModel += "skus," + Skus.ToString() + ",";
            }
            if (CatalogListingIds != null)
            {
                serializedModel += "catalogListingIds," + CatalogListingIds.ToString() + ",";
            }
            if (Currency != null)
            {
                serializedModel += "currency," + Currency + ",";
            }
            if (Country != null)
            {
                serializedModel += "country," + Country + ",";
            }
            if (PaymentProvider != null)
            {
                serializedModel += "paymentProvider," + PaymentProvider + ",";
            }
            if (ExternalTransactionTokens != null)
            {
                serializedModel += "externalTransactionTokens," + ExternalTransactionTokens.ToString() + ",";
            }
            if (DeviceInfo != null)
            {
                serializedModel += "deviceInfo," + DeviceInfo.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a OrderRequest as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Skus != null)
            {
                var skusStringValue = Skus.ToString();
                dictionary.Add("skus", skusStringValue);
            }
            
            if (CatalogListingIds != null)
            {
                var catalogListingIdsStringValue = CatalogListingIds.ToString();
                dictionary.Add("catalogListingIds", catalogListingIdsStringValue);
            }
            
            if (Currency != null)
            {
                var currencyStringValue = Currency.ToString();
                dictionary.Add("currency", currencyStringValue);
            }
            
            if (Country != null)
            {
                var countryStringValue = Country.ToString();
                dictionary.Add("country", countryStringValue);
            }
            
            if (PaymentProvider != null)
            {
                var paymentProviderStringValue = PaymentProvider.ToString();
                dictionary.Add("paymentProvider", paymentProviderStringValue);
            }
            
            return dictionary;
        }
    }
}
