//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Transient credentials for rendering the in-page (embedded) checkout via the payment provider&#39;s JS SDK. Present only when &#x60;uiMode&#x60; is &#x60;embedded&#x60;, and only on the create-order response — it is not persisted and not returned by other endpoints.
    /// </summary>
    [Preserve]
    [DataContract(Name = "order_response_embeddedInfo")]
    internal class OrderResponseEmbeddedInfo
    {
        /// <summary>
        /// Transient credentials for rendering the in-page (embedded) checkout via the payment provider&#39;s JS SDK. Present only when &#x60;uiMode&#x60; is &#x60;embedded&#x60;, and only on the create-order response — it is not persisted and not returned by other endpoints.
        /// </summary>
        /// <param name="clientSecret">Embedded form token used to initialize the provider&#39;s JS SDK.</param>
        /// <param name="publishableKey">The connected account&#39;s public client key (Stripe &#x60;pk_&#x60;), used together with &#x60;clientSecret&#x60; to initialize the JS SDK. Present for providers that require a public client key (Stripe); omitted for providers that mount with the client secret alone (Coda).</param>
        [Preserve]
        public OrderResponseEmbeddedInfo(string clientSecret, string publishableKey = default)
        {
            ClientSecret = clientSecret;
            PublishableKey = publishableKey;
        }

        /// <summary>
        /// Embedded form token used to initialize the provider&#39;s JS SDK.
        /// </summary>
        [Preserve]
        [DataMember(Name = "clientSecret", IsRequired = true, EmitDefaultValue = true)]
        public string ClientSecret{ get; }
        
        /// <summary>
        /// The connected account&#39;s public client key (Stripe &#x60;pk_&#x60;), used together with &#x60;clientSecret&#x60; to initialize the JS SDK. Present for providers that require a public client key (Stripe); omitted for providers that mount with the client secret alone (Coda).
        /// </summary>
        [Preserve]
        [DataMember(Name = "publishableKey", EmitDefaultValue = false)]
        public string PublishableKey{ get; }
    
        /// <summary>
        /// Formats a OrderResponseEmbeddedInfo into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (ClientSecret != null)
            {
                serializedModel += "clientSecret," + ClientSecret + ",";
            }
            if (PublishableKey != null)
            {
                serializedModel += "publishableKey," + PublishableKey;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a OrderResponseEmbeddedInfo as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (ClientSecret != null)
            {
                var clientSecretStringValue = ClientSecret.ToString();
                dictionary.Add("clientSecret", clientSecretStringValue);
            }
            
            if (PublishableKey != null)
            {
                var publishableKeyStringValue = PublishableKey.ToString();
                dictionary.Add("publishableKey", publishableKeyStringValue);
            }
            
            return dictionary;
        }
    }
}
