//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// List of configured payment provider identifiers the calling player is eligible for, listed in priority order, highest first. The list may be empty when no provider is eligible.
    /// </summary>
    [Preserve]
    [DataContract(Name = "payment-providers-response")]
    internal class PaymentProvidersResponse
    {
        /// <summary>
        /// List of configured payment provider identifiers the calling player is eligible for, listed in priority order, highest first. The list may be empty when no provider is eligible.
        /// </summary>
        /// <param name="providers">Ordered, deduplicated list of configured payment provider identifiers eligible for the calling player.</param>
        /// <param name="paymentOptionsPopupEnabled">Server-driven killswitch for the SDK&#39;s payment-options popup. When false, clients should suppress the picker UI and route purchases directly to the native store. Optional; clients treat a missing field as true so older backends (and rollbacks) continue to render the popup. </param>
        [Preserve]
        public PaymentProvidersResponse(List<string> providers, bool? paymentOptionsPopupEnabled = default)
        {
            Providers = providers;
            PaymentOptionsPopupEnabled = paymentOptionsPopupEnabled;
        }

        /// <summary>
        /// Ordered, deduplicated list of configured payment provider identifiers eligible for the calling player.
        /// </summary>
        [Preserve]
        [DataMember(Name = "providers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Providers{ get; }

        /// <summary>
        /// Server-driven killswitch for the SDK&#39;s payment-options popup. When false, clients should suppress the picker UI and route purchases directly to the native store. Optional; clients treat a missing field as true so older backends (and rollbacks) continue to render the popup.
        /// </summary>
        [Preserve]
        [DataMember(Name = "paymentOptionsPopupEnabled", EmitDefaultValue = false)]
        public bool? PaymentOptionsPopupEnabled{ get; }

        /// <summary>
        /// Formats a PaymentProvidersResponse into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (Providers != null)
            {
                serializedModel += "providers," + Providers.ToString() + (PaymentOptionsPopupEnabled != null ? "," : "");
            }
            if (PaymentOptionsPopupEnabled != null)
            {
                serializedModel += "paymentOptionsPopupEnabled," + PaymentOptionsPopupEnabled.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a PaymentProvidersResponse as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (Providers != null)
            {
                var providersStringValue = Providers.ToString();
                dictionary.Add("providers", providersStringValue);
            }

            if (PaymentOptionsPopupEnabled != null)
            {
                var paymentOptionsPopupEnabledStringValue = PaymentOptionsPopupEnabled.ToString();
                dictionary.Add("paymentOptionsPopupEnabled", paymentOptionsPopupEnabledStringValue);
            }

            return dictionary;
        }
    }
}
