//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// Player information for creating an order
    /// </summary>
    [Preserve]
    [DataContract(Name = "player")]
    internal class Player
    {
        /// <summary>
        /// Player information for creating an order
        /// </summary>
        /// <param name="locale">Player&#39;s locale in BCP 47 format</param>
        /// <param name="identity">identity param</param>
        /// <param name="playerId">Unity Player ID (automatically set from authentication token, should not be provided in request)</param>
        /// <param name="displayName">Player&#39;s display name</param>
        /// <param name="metadata">Additional metadata about the player</param>
        [Preserve]
        public Player(string locale, PlayerIdentity identity, string playerId = default, string displayName = default, Dictionary<string, string> metadata = default)
        {
            PlayerId = playerId;
            DisplayName = displayName;
            Locale = locale;
            Metadata = metadata;
            Identity = identity;
        }

        /// <summary>
        /// Unity Player ID (automatically set from authentication token, should not be provided in request)
        /// </summary>
        [Preserve]
        [DataMember(Name = "playerId", EmitDefaultValue = false)]
        public string PlayerId{ get; }
        
        /// <summary>
        /// Player&#39;s display name
        /// </summary>
        [Preserve]
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public string DisplayName{ get; }
        
        /// <summary>
        /// Player&#39;s locale in BCP 47 format
        /// </summary>
        [Preserve]
        [DataMember(Name = "locale", IsRequired = true, EmitDefaultValue = true)]
        public string Locale{ get; }
        
        /// <summary>
        /// Additional metadata about the player
        /// </summary>
        [Preserve]
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata{ get; }
        
        /// <summary>
        /// Parameter identity of Player
        /// </summary>
        [Preserve]
        [DataMember(Name = "identity", IsRequired = true, EmitDefaultValue = true)]
        public PlayerIdentity Identity{ get; }
    
        /// <summary>
        /// Formats a Player into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (PlayerId != null)
            {
                serializedModel += "playerId," + PlayerId + ",";
            }
            if (DisplayName != null)
            {
                serializedModel += "displayName," + DisplayName + ",";
            }
            if (Locale != null)
            {
                serializedModel += "locale," + Locale + ",";
            }
            if (Metadata != null)
            {
                serializedModel += "metadata," + Metadata.ToString() + ",";
            }
            if (Identity != null)
            {
                serializedModel += "identity," + Identity.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a Player as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (PlayerId != null)
            {
                var playerIdStringValue = PlayerId.ToString();
                dictionary.Add("playerId", playerIdStringValue);
            }
            
            if (DisplayName != null)
            {
                var displayNameStringValue = DisplayName.ToString();
                dictionary.Add("displayName", displayNameStringValue);
            }
            
            if (Locale != null)
            {
                var localeStringValue = Locale.ToString();
                dictionary.Add("locale", localeStringValue);
            }
            
            if (Metadata != null)
            {
                var metadataStringValue = Metadata.ToString();
                dictionary.Add("metadata", metadataStringValue);
            }
            
            return dictionary;
        }
    }
}
