//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.PaymentProviderService.Http;



namespace UnityEngine.Purchasing.PaymentProviderService.Models
{
    /// <summary>
    /// A single resolution of a store-specific id to its Unity SKU and product type.
    /// </summary>
    [Preserve]
    [DataContract(Name = "store-override-match")]
    internal class StoreOverrideMatch
    {
        /// <summary>
        /// A single resolution of a store-specific id to its Unity SKU and product type.
        /// </summary>
        /// <param name="uSku">Unity SKU identifier</param>
        /// <param name="type">Product type (e.g., &#39;Consumable&#39;, &#39;NonConsumable&#39;)</param>
        [Preserve]
        public StoreOverrideMatch(string uSku, string type)
        {
            USku = uSku;
            Type = type;
        }

        /// <summary>
        /// Unity SKU identifier
        /// </summary>
        [Preserve]
        [DataMember(Name = "uSku", IsRequired = true, EmitDefaultValue = true)]
        public string USku{ get; }
        
        /// <summary>
        /// Product type (e.g., &#39;Consumable&#39;, &#39;NonConsumable&#39;)
        /// </summary>
        [Preserve]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type{ get; }
    
        /// <summary>
        /// Formats a StoreOverrideMatch into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (USku != null)
            {
                serializedModel += "uSku," + USku + ",";
            }
            if (Type != null)
            {
                serializedModel += "type," + Type;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a StoreOverrideMatch as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (USku != null)
            {
                var uSkuStringValue = USku.ToString();
                dictionary.Add("uSku", uSkuStringValue);
            }
            
            if (Type != null)
            {
                var typeStringValue = Type.ToString();
                dictionary.Add("type", typeStringValue);
            }
            
            return dictionary;
        }
    }
}
