#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.PurchasingAdminApi
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    interface IPaymentProviderConfigurationApi : IApiAccessor
    {
        /// <summary>
        /// Get Payment Provider Configuration
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<PaymentProviderConfigurationResponse> GetPaymentProviderConfiguration(string projectId, string environmentId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Create or Update Payment Provider Configuration
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="paymentProviderConfigurationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<PaymentProviderConfigurationResponse> CreateOrUpdatePaymentProviderConfiguration(string projectId, string environmentId, PaymentProviderConfigurationRequest paymentProviderConfigurationRequest, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Global Redirect URLs
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<RedirectUrlsResponse> GetRedirectUrls(string projectId, string environmentId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Set Global Redirect URLs
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="redirectUrlsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<RedirectUrlsResponse> PutRedirectUrls(string projectId, string environmentId, RedirectUrlsRequest redirectUrlsRequest, CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Provider Targeting Configuration
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<TargetingResponse> GetTargeting(string projectId, string environmentId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Update Provider Targeting Configuration
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="targetingRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<TargetingResponse> UpdateTargeting(string projectId, string environmentId, TargetingRequest targetingRequest, CancellationToken cancellationToken = default);

        /// <summary>
        /// Upsert Specific Payment Provider Configuration
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="paymentProviderId">Payment provider identifier</param>
        /// <param name="upsertSpecificPaymentProviderConfigurationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<PaymentProviderConfigurationResponse> UpsertSpecificPaymentProviderConfiguration(string projectId, string environmentId, string paymentProviderId, UpsertSpecificPaymentProviderConfigurationRequest upsertSpecificPaymentProviderConfigurationRequest, CancellationToken cancellationToken = default);

        /// <summary>
        /// Start OAuth Authorization Flow
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="paymentProviderId">Payment provider identifier</param>
        /// <param name="mode">OAuth mode for the payment provider (optional, default to live)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<OAuthStartResponse> HandleOAuthStart(string projectId, string environmentId, string paymentProviderId, string mode = default(string), CancellationToken cancellationToken = default);

        /// <summary>
        /// Generate Signup URL
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="signupURLRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<SignupURLResponse> GenerateSignupURL(string projectId, string environmentId, SignupURLRequest signupURLRequest, CancellationToken cancellationToken = default);

        /// <summary>
        /// Copy CodaPay Configuration
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="copyConfigurationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation CopyCodaPayConfiguration(string projectId, string environmentId, CopyConfigurationRequest copyConfigurationRequest, CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    partial class PaymentProviderConfigurationApi : IPaymentProviderConfigurationApi
    {
        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IApiClient Client { get; }

        /// <summary>
        /// Gets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IApiConfiguration Configuration { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentProviderConfigurationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="apiClient">The client interface for synchronous API access.</param>
        public PaymentProviderConfigurationApi(IApiClient apiClient)
        {
            if (apiClient == null) throw new ArgumentNullException("apiClient");

            this.Client = apiClient;
            this.Configuration = new ApiConfiguration()
            {
                BasePath = "https://services.unity.com/api/iap/v1"
            };
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentProviderConfigurationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="apiClient">The client interface for synchronous API access.</param>
        /// <param name="apiConfiguration">The configuration object.</param>
        public PaymentProviderConfigurationApi(IApiClient apiClient, IApiConfiguration apiConfiguration)
        {
            if (apiClient == null) throw new ArgumentNullException("apiClient");
            if (apiConfiguration == null) throw new ArgumentNullException("apiConfiguration");

            this.Client = apiClient;
            this.Configuration = apiConfiguration;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <returns>The base path</returns>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Get Payment Provider Configuration Retrieve payment provider configuration for the specified project and environment
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<PaymentProviderConfigurationResponse> GetPaymentProviderConfiguration(string projectId, string environmentId, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.GetPaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.GetPaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.GetPaymentProviderConfiguration";


            return this.Client.Get<PaymentProviderConfigurationResponse>("/projects/{projectId}/environments/{environmentId}/payment-provider/configuration", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Create or Update Payment Provider Configuration Create or update payment provider configuration for the specified project and environment
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="paymentProviderConfigurationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<PaymentProviderConfigurationResponse> CreateOrUpdatePaymentProviderConfiguration(string projectId, string environmentId, PaymentProviderConfigurationRequest paymentProviderConfigurationRequest, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.CreateOrUpdatePaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.CreateOrUpdatePaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (paymentProviderConfigurationRequest == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'paymentProviderConfigurationRequest' when calling PaymentProviderConfigurationApi.CreateOrUpdatePaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.Data = paymentProviderConfigurationRequest;

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.CreateOrUpdatePaymentProviderConfiguration";


            return this.Client.Post<PaymentProviderConfigurationResponse>("/projects/{projectId}/environments/{environmentId}/payment-provider/configuration", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Get Global Redirect URLs Retrieve the global success and failure redirect URLs for the specified project and environment
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<RedirectUrlsResponse> GetRedirectUrls(string projectId, string environmentId, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<RedirectUrlsResponse>(new ApiResponse<RedirectUrlsResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.GetRedirectUrls",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<RedirectUrlsResponse>(new ApiResponse<RedirectUrlsResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.GetRedirectUrls",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.GetRedirectUrls";


            return this.Client.Get<RedirectUrlsResponse>("/projects/{projectId}/environments/{environmentId}/payment-provider/configuration/redirect-urls", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Set Global Redirect URLs Set the global success and failure redirect URLs for the specified project and environment
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="redirectUrlsRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<RedirectUrlsResponse> PutRedirectUrls(string projectId, string environmentId, RedirectUrlsRequest redirectUrlsRequest, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<RedirectUrlsResponse>(new ApiResponse<RedirectUrlsResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.PutRedirectUrls",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<RedirectUrlsResponse>(new ApiResponse<RedirectUrlsResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.PutRedirectUrls",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (redirectUrlsRequest == null)
            {
                return new ApiOperation<RedirectUrlsResponse>(new ApiResponse<RedirectUrlsResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'redirectUrlsRequest' when calling PaymentProviderConfigurationApi.PutRedirectUrls",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.Data = redirectUrlsRequest;

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.PutRedirectUrls";


            return this.Client.Put<RedirectUrlsResponse>("/projects/{projectId}/environments/{environmentId}/payment-provider/configuration/redirect-urls", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Get Provider Targeting Configuration Retrieve tag-to-provider targeting configuration for the specified project and environment
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<TargetingResponse> GetTargeting(string projectId, string environmentId, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<TargetingResponse>(new ApiResponse<TargetingResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.GetTargeting",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<TargetingResponse>(new ApiResponse<TargetingResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.GetTargeting",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.GetTargeting";


            return this.Client.Get<TargetingResponse>("/projects/{projectId}/environments/{environmentId}/targeting", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Update Provider Targeting Configuration Replace the tag-to-provider targeting configuration atomically
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="targetingRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<TargetingResponse> UpdateTargeting(string projectId, string environmentId, TargetingRequest targetingRequest, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<TargetingResponse>(new ApiResponse<TargetingResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.UpdateTargeting",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<TargetingResponse>(new ApiResponse<TargetingResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.UpdateTargeting",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (targetingRequest == null)
            {
                return new ApiOperation<TargetingResponse>(new ApiResponse<TargetingResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'targetingRequest' when calling PaymentProviderConfigurationApi.UpdateTargeting",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.Data = targetingRequest;

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.UpdateTargeting";


            return this.Client.Post<TargetingResponse>("/projects/{projectId}/environments/{environmentId}/targeting", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Upsert Specific Payment Provider Configuration Create or update configuration for a specific payment provider
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="paymentProviderId">Payment provider identifier</param>
        /// <param name="upsertSpecificPaymentProviderConfigurationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<PaymentProviderConfigurationResponse> UpsertSpecificPaymentProviderConfiguration(string projectId, string environmentId, string paymentProviderId, UpsertSpecificPaymentProviderConfigurationRequest upsertSpecificPaymentProviderConfigurationRequest, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.UpsertSpecificPaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.UpsertSpecificPaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (paymentProviderId == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'paymentProviderId' when calling PaymentProviderConfigurationApi.UpsertSpecificPaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (upsertSpecificPaymentProviderConfigurationRequest == null)
            {
                return new ApiOperation<PaymentProviderConfigurationResponse>(new ApiResponse<PaymentProviderConfigurationResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'upsertSpecificPaymentProviderConfigurationRequest' when calling PaymentProviderConfigurationApi.UpsertSpecificPaymentProviderConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("paymentProviderId", ApiUtils.ParameterToString(Configuration, paymentProviderId));
            apiRequestOptions.Data = upsertSpecificPaymentProviderConfigurationRequest;

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.UpsertSpecificPaymentProviderConfiguration";


            return this.Client.Post<PaymentProviderConfigurationResponse>("/projects/{projectId}/environments/{environmentId}/payment-providers/{paymentProviderId}/configuration", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Start OAuth Authorization Flow Start OAuth authorization with the payment provider. Returns the provider&#39;s authorization URL.
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="paymentProviderId">Payment provider identifier</param>
        /// <param name="mode">OAuth mode for the payment provider (optional, default to live)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<OAuthStartResponse> HandleOAuthStart(string projectId, string environmentId, string paymentProviderId, string mode = default(string), CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<OAuthStartResponse>(new ApiResponse<OAuthStartResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.HandleOAuthStart",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<OAuthStartResponse>(new ApiResponse<OAuthStartResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.HandleOAuthStart",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (paymentProviderId == null)
            {
                return new ApiOperation<OAuthStartResponse>(new ApiResponse<OAuthStartResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'paymentProviderId' when calling PaymentProviderConfigurationApi.HandleOAuthStart",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("paymentProviderId", ApiUtils.ParameterToString(Configuration, paymentProviderId));
            if (mode != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "mode", mode));
            }

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.HandleOAuthStart";


            return this.Client.Get<OAuthStartResponse>("/projects/{projectId}/environments/{environmentId}/payment-providers/{paymentProviderId}/oauth/start", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Generate Signup URL Generates a portal signup URL with an embedded Unity token for account linking.
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="signupURLRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<SignupURLResponse> GenerateSignupURL(string projectId, string environmentId, SignupURLRequest signupURLRequest, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<SignupURLResponse>(new ApiResponse<SignupURLResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.GenerateSignupURL",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation<SignupURLResponse>(new ApiResponse<SignupURLResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.GenerateSignupURL",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (signupURLRequest == null)
            {
                return new ApiOperation<SignupURLResponse>(new ApiResponse<SignupURLResponse>()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'signupURLRequest' when calling PaymentProviderConfigurationApi.GenerateSignupURL",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            string[] _accepts = new string[] {
                "application/json",
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.Data = signupURLRequest;

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.GenerateSignupURL";


            return this.Client.Post<SignupURLResponse>("/projects/{projectId}/environments/{environmentId}/payment-providers/codapay/signup-url", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Copy CodaPay Configuration Copies an existing CodaPay configuration from another environment in the same project to the current environment.
        /// </summary>
        /// <param name="projectId">ID of the Unity project.</param>
        /// <param name="environmentId">ID of the Unity environment.</param>
        /// <param name="copyConfigurationRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation CopyCodaPayConfiguration(string projectId, string environmentId, CopyConfigurationRequest copyConfigurationRequest, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation(new ApiResponse()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'projectId' when calling PaymentProviderConfigurationApi.CopyCodaPayConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (environmentId == null)
            {
                return new ApiOperation(new ApiResponse()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'environmentId' when calling PaymentProviderConfigurationApi.CopyCodaPayConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            if (copyConfigurationRequest == null)
            {
                return new ApiOperation(new ApiResponse()
                {
                    StatusCode = -1,
                    ErrorText = "Missing required parameter 'copyConfigurationRequest' when calling PaymentProviderConfigurationApi.CopyCodaPayConfiguration",
                    ErrorType = ApiErrorType.InvalidParameters
                });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            string[] _accepts = new string[] {
                "application/problem+json"
            };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.Data = copyConfigurationRequest;

            apiRequestOptions.Operation = "PaymentProviderConfigurationApi.CopyCodaPayConfiguration";


            return this.Client.Post("/projects/{projectId}/environments/{environmentId}/payment-providers/codapay/configuration/copy", apiRequestOptions, this.Configuration, cancellationToken);
        }
    }
}
#endif
