#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.PurchasingAdminApi
{
    /// <summary>
    /// Localized product name and description for a single language.
    /// </summary>
    [DataContract(Name = "CatalogProductDetail")]
    [Preserve]
    public partial class CatalogProductDetail
    {
        /// <summary>
        /// BCP 47 language tag.
        /// </summary>
        /// <value>BCP 47 language tag.</value>
        [DataMember(Name = "language", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string Language { get; set; }

        /// <summary>
        /// Localized product title.
        /// </summary>
        /// <value>Localized product title.</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string Title { get; set; }

        /// <summary>
        /// Localized product description.
        /// </summary>
        /// <value>Localized product description.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        [Preserve]
        public string Description { get; set; }

        /// <summary>
        /// Optional localized subtitle (Apple only).
        /// </summary>
        /// <value>Optional localized subtitle (Apple only).</value>
        [DataMember(Name = "subtitle", EmitDefaultValue = false)]
        [Preserve]
        public string Subtitle { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogProductDetail" /> class.
        /// </summary>
        /// <param name="language">BCP 47 language tag. (required).</param>
        /// <param name="title">Localized product title. (required).</param>
        /// <param name="description">Localized product description. (required).</param>
        /// <param name="subtitle">Optional localized subtitle (Apple only)..</param>
        [Preserve]
        public CatalogProductDetail(string language = default(string), string title = default(string), string description = default(string), string subtitle = default(string))
        {
            if (language == null)
            {
                throw new ArgumentNullException("language is a required property for CatalogProductDetail and cannot be null");
            }
            this.Language = language;
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for CatalogProductDetail and cannot be null");
            }
            this.Title = title;
            this.Description = description;
            this.Subtitle = subtitle;
        }
    }

}
#endif