#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.PurchasingAdminApi
{
    /// <summary>
    /// CodaPayConfiguration
    /// </summary>
    [DataContract(Name = "CodaPayConfiguration")]
    [Preserve]
    public partial class CodaPayConfiguration
    {
        /// <summary>
        /// CodaPay title name
        /// </summary>
        /// <value>CodaPay title name</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        [Preserve]
        public string Title { get; set; }

        /// <summary>
        /// CodaPay title identifier
        /// </summary>
        /// <value>CodaPay title identifier</value>
        [DataMember(Name = "titleId", EmitDefaultValue = false)]
        [Preserve]
        public string TitleId { get; set; }

        /// <summary>
        /// CodaPay title product name
        /// </summary>
        /// <value>CodaPay title product name</value>
        [DataMember(Name = "titleProduct", EmitDefaultValue = false)]
        [Preserve]
        public string TitleProduct { get; set; }

        /// <summary>
        /// CodaPay title product identifier
        /// </summary>
        /// <value>CodaPay title product identifier</value>
        [DataMember(Name = "titleProductId", EmitDefaultValue = false)]
        [Preserve]
        public string TitleProductId { get; set; }

        /// <summary>
        /// CodaPay project identifier
        /// </summary>
        /// <value>CodaPay project identifier</value>
        [DataMember(Name = "codaProjectId", EmitDefaultValue = false)]
        [Preserve]
        public int CodaProjectId { get; set; }

        /// <summary>
        /// Whether the CodaPay environment is production
        /// </summary>
        /// <value>Whether the CodaPay environment is production</value>
        [DataMember(Name = "isProduction", EmitDefaultValue = true)]
        [Preserve]
        public bool IsProduction { get; set; }

        /// <summary>
        /// CodaPay settlement name
        /// </summary>
        /// <value>CodaPay settlement name</value>
        [DataMember(Name = "settlementName", EmitDefaultValue = false)]
        [Preserve]
        public string SettlementName { get; set; }

        /// <summary>
        /// Whether KYC has been submitted
        /// </summary>
        /// <value>Whether KYC has been submitted</value>
        [DataMember(Name = "kycSubmitted", EmitDefaultValue = true)]
        [Preserve]
        public bool KycSubmitted { get; set; }

        /// <summary>
        /// Whether KYC has been verified
        /// </summary>
        /// <value>Whether KYC has been verified</value>
        [DataMember(Name = "kycVerified", EmitDefaultValue = true)]
        [Preserve]
        public bool KycVerified { get; set; }

        /// <summary>
        /// Whether the contract has been signed
        /// </summary>
        /// <value>Whether the contract has been signed</value>
        [DataMember(Name = "contractSigned", EmitDefaultValue = true)]
        [Preserve]
        public bool ContractSigned { get; set; }

        /// <summary>
        /// Last update timestamp
        /// </summary>
        /// <value>Last update timestamp</value>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        [Preserve]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CodaPayConfiguration" /> class.
        /// </summary>
        /// <param name="title">CodaPay title name.</param>
        /// <param name="titleId">CodaPay title identifier.</param>
        /// <param name="titleProduct">CodaPay title product name.</param>
        /// <param name="titleProductId">CodaPay title product identifier.</param>
        /// <param name="codaProjectId">CodaPay project identifier.</param>
        /// <param name="isProduction">Whether the CodaPay environment is production.</param>
        /// <param name="settlementName">CodaPay settlement name.</param>
        /// <param name="kycSubmitted">Whether KYC has been submitted.</param>
        /// <param name="kycVerified">Whether KYC has been verified.</param>
        /// <param name="contractSigned">Whether the contract has been signed.</param>
        /// <param name="updatedAt">Last update timestamp.</param>
        [Preserve]
        public CodaPayConfiguration(string title = default(string), string titleId = default(string), string titleProduct = default(string), string titleProductId = default(string), int codaProjectId = default(int), bool isProduction = default(bool), string settlementName = default(string), bool kycSubmitted = default(bool), bool kycVerified = default(bool), bool contractSigned = default(bool), DateTime updatedAt = default(DateTime))
        {
            this.Title = title;
            this.TitleId = titleId;
            this.TitleProduct = titleProduct;
            this.TitleProductId = titleProductId;
            this.CodaProjectId = codaProjectId;
            this.IsProduction = isProduction;
            this.SettlementName = settlementName;
            this.KycSubmitted = kycSubmitted;
            this.KycVerified = kycVerified;
            this.ContractSigned = contractSigned;
            this.UpdatedAt = updatedAt;
        }
    }

}
#endif