#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.PurchasingAdminApi
{
    /// <summary>
    /// PaymentProviderConfigurationRequest
    /// </summary>
    [DataContract(Name = "PaymentProviderConfigurationRequest")]
    [Preserve]
    public partial class PaymentProviderConfigurationRequest
    {
        /// <summary>
        /// Legacy single-provider selection. When set, all orders without a tag-based match fall back to this provider. Optional; if omitted on update, the existing value is preserved. Will be removed once the dashboard adopts tag-based routing UI. &#x60;mock&#x60; is for development and testing only. 
        /// </summary>
        /// <value>Legacy single-provider selection. When set, all orders without a tag-based match fall back to this provider. Optional; if omitted on update, the existing value is preserved. Will be removed once the dashboard adopts tag-based routing UI. &#x60;mock&#x60; is for development and testing only. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TargetPaymentProviderEnum
        {
            /// <summary>
            /// Enum Codapay for value: codapay
            /// </summary>
            [EnumMember(Value = "codapay")]
            Codapay = 1,

            /// <summary>
            /// Enum Stripe for value: stripe
            /// </summary>
            [EnumMember(Value = "stripe")]
            Stripe = 2,

            /// <summary>
            /// Enum Mock for value: mock
            /// </summary>
            [EnumMember(Value = "mock")]
            Mock = 3

        }

        /// <summary>
        /// Legacy single-provider selection. When set, all orders without a tag-based match fall back to this provider. Optional; if omitted on update, the existing value is preserved. Will be removed once the dashboard adopts tag-based routing UI. &#x60;mock&#x60; is for development and testing only. 
        /// </summary>
        /// <value>Legacy single-provider selection. When set, all orders without a tag-based match fall back to this provider. Optional; if omitted on update, the existing value is preserved. Will be removed once the dashboard adopts tag-based routing UI. &#x60;mock&#x60; is for development and testing only. </value>
        [DataMember(Name = "targetPaymentProvider", EmitDefaultValue = false)]
        [Preserve]
        public TargetPaymentProviderEnum? TargetPaymentProvider { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentProviderConfigurationRequest" /> class.
        /// </summary>
        /// <param name="targetPaymentProvider">Legacy single-provider selection. When set, all orders without a tag-based match fall back to this provider. Optional; if omitted on update, the existing value is preserved. Will be removed once the dashboard adopts tag-based routing UI. &#x60;mock&#x60; is for development and testing only. .</param>
        [Preserve]
        public PaymentProviderConfigurationRequest(TargetPaymentProviderEnum? targetPaymentProvider = default(TargetPaymentProviderEnum?))
        {
            this.TargetPaymentProvider = targetPaymentProvider;
        }
    }

}
#endif