#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.PurchasingAdminApi
{
    /// <summary>
    /// TargetingResponse
    /// </summary>
    [DataContract(Name = "TargetingResponse")]
    [Preserve]
    public partial class TargetingResponse
    {

        /// <summary>
        /// Tag-to-provider mappings. Keys are tags, values are ordered lists of payment providers.
        /// </summary>
        /// <value>Tag-to-provider mappings. Keys are tags, values are ordered lists of payment providers.</value>
        [DataMember(Name = "mappings", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public Dictionary<string, List<string>> Mappings { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TargetingResponse" /> class.
        /// </summary>
        /// <param name="mappings">Tag-to-provider mappings. Keys are tags, values are ordered lists of payment providers. (required).</param>
        [Preserve]
        public TargetingResponse(Dictionary<string, List<string>> mappings = default(Dictionary<string, List<string>>))
        {
            if (mappings == null)
            {
                throw new ArgumentNullException("mappings is a required property for TargetingResponse and cannot be null");
            }
            this.Mappings = mappings;
        }
    }

}
#endif