#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.PurchasingAdminApi
{
    /// <summary>
    /// Validation error response when a value provided from the client does not pass validation on server.
    /// </summary>
    [DataContract(Name = "ValidationErrorResponse_1")]
    [Preserve]
    public partial class ValidationErrorResponse1
    {
        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        [Preserve]
        public List<ValidationError> Errors { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ValidationErrorResponse1" /> class.
        /// </summary>
        /// <param name="errors">errors.</param>
        [Preserve]
        public ValidationErrorResponse1(List<ValidationError> errors = default(List<ValidationError>))
        {
            this.Errors = errors;
        }
    }

}
#endif