#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// BatchDeleteResponse
    /// </summary>
    [DataContract(Name = "batchDeleteResponse")]
    [Preserve]
    public partial class BatchDeleteResponse
    {
        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        [Preserve]
        public List<DeleteError> Error { get; set; }

        /// <summary>
        /// Gets or Sets DeletedIds
        /// </summary>
        [DataMember(Name = "deletedIds", EmitDefaultValue = false)]
        [Preserve]
        public List<string> DeletedIds { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchDeleteResponse" /> class.
        /// </summary>
        /// <param name="error">error.</param>
        /// <param name="deletedIds">deletedIds.</param>
        [Preserve]
        public BatchDeleteResponse(List<DeleteError> error = default(List<DeleteError>), List<string> deletedIds = default(List<string>))
        {
            this.Error = error;
            this.DeletedIds = deletedIds;
        }
    }

}
#endif