#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// ClientFile
    /// </summary>
    [DataContract(Name = "clientFile")]
    [Preserve]
    internal partial class ClientFile
    {
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        [Preserve]
        public ResourceType? Type { get; set; }
        /// <summary>
        /// Base64-encoded SHA-256 hash of the file content (44 characters in Base64, including padding). MD5 (deprecated) is accepted for legacy compatibility.
        /// </summary>
        /// <value>Base64-encoded SHA-256 hash of the file content (44 characters in Base64, including padding). MD5 (deprecated) is accepted for legacy compatibility.</value>
        [DataMember(Name = "contentHash", EmitDefaultValue = false)]
        [Preserve]
        public string ContentHash { get; set; }

        /// <summary>
        /// Gets or Sets ContentSize
        /// </summary>
        [DataMember(Name = "contentSize", EmitDefaultValue = false)]
        [Preserve]
        public long ContentSize { get; set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        [Preserve]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets ContentUri
        /// </summary>
        [DataMember(Name = "contentUri", EmitDefaultValue = false)]
        [Preserve]
        public string ContentUri { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [Preserve]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        [Preserve]
        public string Path { get; set; }

        /// <summary>
        /// Reserved. Optional pre-defined sort key.
        /// </summary>
        /// <value>Reserved. Optional pre-defined sort key.</value>
        [DataMember(Name = "sortIndex", EmitDefaultValue = false)]
        [Preserve]
        public long SortIndex { get; set; }

        /// <summary>
        /// Gets or Sets VariantTag
        /// </summary>
        [DataMember(Name = "variantTag", EmitDefaultValue = false)]
        [Preserve]
        public List<string> VariantTag { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientFile" /> class.
        /// </summary>
        /// <param name="contentHash">Base64-encoded SHA-256 hash of the file content (44 characters in Base64, including padding). MD5 (deprecated) is accepted for legacy compatibility..</param>
        /// <param name="contentSize">contentSize.</param>
        /// <param name="contentType">contentType.</param>
        /// <param name="contentUri">contentUri.</param>
        /// <param name="id">id.</param>
        /// <param name="path">path.</param>
        /// <param name="sortIndex">Reserved. Optional pre-defined sort key..</param>
        /// <param name="type">type.</param>
        /// <param name="variantTag">variantTag.</param>
        [Preserve]
        public ClientFile(string contentHash = default(string), long contentSize = default(long), string contentType = default(string), string contentUri = default(string), string id = default(string), string path = default(string), long sortIndex = default(long), ResourceType? type = default(ResourceType?), List<string> variantTag = default(List<string>))
        {
            this.ContentHash = contentHash;
            this.ContentSize = contentSize;
            this.ContentType = contentType;
            this.ContentUri = contentUri;
            this.Id = id;
            this.Path = path;
            this.SortIndex = sortIndex;
            this.Type = type;
            this.VariantTag = variantTag;
        }
    }

}
#endif