#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;
using System.Reflection;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// JSON Schema URIs that define the structure of the config
    /// </summary>
    [JsonConverter(typeof(ConfigCreateBatchSchemaJsonConverter))]
    [DataContract(Name = "configCreateBatch__schema")]
    [Preserve]
    internal partial class ConfigCreateBatchSchema : AbstractOpenAPISchema, IEquatable<ConfigCreateBatchSchema>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigCreateBatchSchema" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        [Preserve]
        public ConfigCreateBatchSchema(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigCreateBatchSchema" /> class
        /// with the <see cref="List{String}" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of List&lt;string&gt;.</param>
        [Preserve]
        public ConfigCreateBatchSchema(List<string> actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(List<string>))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: List<string>, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `List&lt;string&gt;`. If the actual instance is not `List&lt;string&gt;`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of List&lt;string&gt;</returns>
        public List<string> GetListUri()
        {
            return (List<string>)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConfigCreateBatchSchema {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ConfigCreateBatchSchema.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ConfigCreateBatchSchema
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ConfigCreateBatchSchema</returns>
        public static ConfigCreateBatchSchema FromJson(string jsonString)
        {
            ConfigCreateBatchSchema newConfigCreateBatchSchema = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newConfigCreateBatchSchema;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                if (typeof(List<string>).GetProperty("AdditionalProperties") == null)
                {
                    newConfigCreateBatchSchema = new ConfigCreateBatchSchema(JsonConvert.DeserializeObject<List<string>>(jsonString, ConfigCreateBatchSchema.SerializerSettings));
                }
                else
                {
                    newConfigCreateBatchSchema = new ConfigCreateBatchSchema(JsonConvert.DeserializeObject<List<string>>(jsonString, ConfigCreateBatchSchema.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("List<string>");
                match++;
            }
            catch (Exception)
            {
            }

            try
            {
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                {
                    newConfigCreateBatchSchema = new ConfigCreateBatchSchema(JsonConvert.DeserializeObject<string>(jsonString, ConfigCreateBatchSchema.SerializerSettings));
                }
                else
                {
                    newConfigCreateBatchSchema = new ConfigCreateBatchSchema(JsonConvert.DeserializeObject<string>(jsonString, ConfigCreateBatchSchema.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception)
            {
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            return newConfigCreateBatchSchema;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConfigCreateBatchSchema);
        }

        /// <summary>
        /// Returns true if ConfigCreateBatchSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of ConfigCreateBatchSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConfigCreateBatchSchema input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }
    }

    /// <summary>
    /// Custom JSON converter for ConfigCreateBatchSchema
    /// </summary>
    [Preserve]
    class ConfigCreateBatchSchemaJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ConfigCreateBatchSchema).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ConfigCreateBatchSchema.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
#endif