#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// ConfigCreateBatch
    /// </summary>
    [DataContract(Name = "configCreateBatch")]
    [Preserve]
    public partial class ConfigCreateBatch : Dictionary<String, ApiObject>
    {
        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "$path", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets VariantTag
        /// </summary>
        [DataMember(Name = "$variantTag", EmitDefaultValue = false)]
        [Preserve]
        public List<string> VariantTag { get; set; }

        /// <summary>
        /// JSON Schema URIs that define the structure of the config
        /// </summary>
        /// <value>JSON Schema URIs that define the structure of the config</value>
        [DataMember(Name = "$schema", EmitDefaultValue = false)]
        [Preserve]
        public List<string> Schema { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "$metadata", EmitDefaultValue = false)]
        [Preserve]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        [Preserve]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigCreateBatch" /> class.
        /// </summary>
        /// <param name="path">path (required).</param>
        /// <param name="variantTag">variantTag.</param>
        /// <param name="schema">JSON Schema URIs that define the structure of the config.</param>
        /// <param name="metadata">metadata.</param>
        [Preserve]
        public ConfigCreateBatch(string path = default(string), List<string> variantTag = default(List<string>), List<string> schema = default(List<string>), Object metadata = default(Object)) : base()
        {
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for ConfigCreateBatch and cannot be null");
            }
            this.Path = path;
            this.VariantTag = variantTag;
            this.Schema = schema;
            this.Metadata = metadata;
            this.AdditionalProperties = new Dictionary<string, object>();
        }
    }

}
#endif