#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// ConfigFileUpdate
    /// </summary>
    [DataContract(Name = "configFileUpdate")]
    [Preserve]
    internal partial class ConfigFileUpdate : Dictionary<String, ApiObject>
    {
        /// <summary>
        /// Metadata about the config
        /// </summary>
        /// <value>Metadata about the config</value>
        [DataMember(Name = "$metadata", EmitDefaultValue = false)]
        [Preserve]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [DataMember(Name = "$schema", EmitDefaultValue = false)]
        [Preserve]
        public ConfigCreateBatchSchema Schema { get; set; }

        /// <summary>
        /// Reserved. Optional pre-defined sort key. When omitted, the server assigns a default derived from the creation timestamp.
        /// </summary>
        /// <value>Reserved. Optional pre-defined sort key. When omitted, the server assigns a default derived from the creation timestamp.</value>
        [DataMember(Name = "$sortIndex", EmitDefaultValue = false)]
        [Preserve]
        public long SortIndex { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        [Preserve]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigFileUpdate" /> class.
        /// </summary>
        /// <param name="metadata">Metadata about the config.</param>
        /// <param name="schema">schema.</param>
        /// <param name="sortIndex">Reserved. Optional pre-defined sort key. When omitted, the server assigns a default derived from the creation timestamp..</param>
        [Preserve]
        public ConfigFileUpdate(Object metadata = default(Object), ConfigCreateBatchSchema schema = default(ConfigCreateBatchSchema), long sortIndex = default(long)) : base()
        {
            this.Metadata = metadata;
            this.Schema = schema;
            this.SortIndex = sortIndex;
            this.AdditionalProperties = new Dictionary<string, object>();
        }
    }

}
#endif