#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// A config document with all matching live variants. Config variants never expose contentUri.
    /// </summary>
    [DataContract(Name = "configMetadataWithContent")]
    [Preserve]
    internal partial class ConfigMetadataWithContent
    {
        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        internal enum TypeEnum
        {
            /// <summary>
            /// Enum Config for value: config
            /// </summary>
            [EnumMember(Value = "config")]
            Config = 1

        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [DataMember(Name = "contentType", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets Schemas
        /// </summary>
        [DataMember(Name = "schemas", EmitDefaultValue = false)]
        [Preserve]
        public List<string> Schemas { get; set; }

        /// <summary>
        /// Gets or Sets SortIndex
        /// </summary>
        [DataMember(Name = "sortIndex", EmitDefaultValue = false)]
        [Preserve]
        public long SortIndex { get; set; }

        /// <summary>
        /// Gets or Sets Variants
        /// </summary>
        [DataMember(Name = "variants", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public List<ConfigVariantWithContent> Variants { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigMetadataWithContent" /> class.
        /// </summary>
        /// <param name="contentType">contentType (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="path">path (required).</param>
        /// <param name="schemas">schemas.</param>
        /// <param name="sortIndex">sortIndex.</param>
        /// <param name="type">type (required).</param>
        /// <param name="variants">variants (required).</param>
        [Preserve]
        public ConfigMetadataWithContent(string contentType = default(string), string id = default(string), string path = default(string), List<string> schemas = default(List<string>), long sortIndex = default(long), TypeEnum type = default(TypeEnum), List<ConfigVariantWithContent> variants = default(List<ConfigVariantWithContent>))
        {
            if (contentType == null)
            {
                throw new ArgumentNullException("contentType is a required property for ConfigMetadataWithContent and cannot be null");
            }
            this.ContentType = contentType;
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ConfigMetadataWithContent and cannot be null");
            }
            this.Id = id;
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for ConfigMetadataWithContent and cannot be null");
            }
            this.Path = path;
            this.Type = type;
            if (variants == null)
            {
                throw new ArgumentNullException("variants is a required property for ConfigMetadataWithContent and cannot be null");
            }
            this.Variants = variants;
            this.Schemas = schemas;
            this.SortIndex = sortIndex;
        }
    }

}
#endif