#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// FileUpdate
    /// </summary>
    [DataContract(Name = "fileUpdate")]
    [Preserve]
    internal partial class FileUpdate
    {
        /// <summary>
        /// Base64-encoded SHA-256 (44 chars) or MD5 (22–24 chars, deprecated) hash of the file content
        /// </summary>
        /// <value>Base64-encoded SHA-256 (44 chars) or MD5 (22–24 chars, deprecated) hash of the file content</value>
        [DataMember(Name = "contentHash", EmitDefaultValue = false)]
        [Preserve]
        public string ContentHash { get; set; }

        /// <summary>
        /// Gets or Sets ContentSize
        /// </summary>
        [DataMember(Name = "contentSize", EmitDefaultValue = false)]
        [Preserve]
        public long ContentSize { get; set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        [Preserve]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        [Preserve]
        public Object Metadata { get; set; }

        /// <summary>
        /// Reserved. Optional pre-defined sort key. When omitted, the server assigns a default derived from the creation timestamp.
        /// </summary>
        /// <value>Reserved. Optional pre-defined sort key. When omitted, the server assigns a default derived from the creation timestamp.</value>
        [DataMember(Name = "sortIndex", EmitDefaultValue = false)]
        [Preserve]
        public long SortIndex { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileUpdate" /> class.
        /// </summary>
        /// <param name="contentHash">Base64-encoded SHA-256 (44 chars) or MD5 (22–24 chars, deprecated) hash of the file content.</param>
        /// <param name="contentSize">contentSize.</param>
        /// <param name="contentType">contentType.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="sortIndex">Reserved. Optional pre-defined sort key. When omitted, the server assigns a default derived from the creation timestamp..</param>
        [Preserve]
        public FileUpdate(string contentHash = default(string), long contentSize = default(long), string contentType = default(string), Object metadata = default(Object), long sortIndex = default(long))
        {
            this.ContentHash = contentHash;
            this.ContentSize = contentSize;
            this.ContentType = contentType;
            this.Metadata = metadata;
            this.SortIndex = sortIndex;
        }
    }

}
#endif