#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// FileDeleteBatch
    /// </summary>
    [DataContract(Name = "fileDeleteBatch")]
    [Preserve]
    public partial class FileDeleteBatch
    {
        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets VariantTag
        /// </summary>
        [DataMember(Name = "variantTag", EmitDefaultValue = false)]
        [Preserve]
        public List<string> VariantTag { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileDeleteBatch" /> class.
        /// </summary>
        /// <param name="path">path (required).</param>
        /// <param name="variantTag">variantTag.</param>
        [Preserve]
        public FileDeleteBatch(string path = default(string), List<string> variantTag = default(List<string>))
        {
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for FileDeleteBatch and cannot be null");
            }
            this.Path = path;
            this.VariantTag = variantTag;
        }
    }

}
#endif