#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// FileWithState
    /// </summary>
    [DataContract(Name = "fileWithState")]
    [Preserve]
    internal partial class FileWithState
    {
        /// <summary>
        /// Defines State
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        internal enum StateEnum
        {
            /// <summary>
            /// Enum Added for value: added
            /// </summary>
            [EnumMember(Value = "added")]
            Added = 1,

            /// <summary>
            /// Enum Deleted for value: deleted
            /// </summary>
            [EnumMember(Value = "deleted")]
            Deleted = 2,

            /// <summary>
            /// Enum Modified for value: modified
            /// </summary>
            [EnumMember(Value = "modified")]
            Modified = 3,

            /// <summary>
            /// Enum Unchanged for value: unchanged
            /// </summary>
            [EnumMember(Value = "unchanged")]
            Unchanged = 4

        }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        [Preserve]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        [Preserve]
        public ResourceType? Type { get; set; }
        /// <summary>
        /// Gets or Sets Complete
        /// </summary>
        [DataMember(Name = "complete", EmitDefaultValue = true)]
        [Preserve]
        public bool Complete { get; set; }

        /// <summary>
        /// Gets or Sets ContentSize
        /// </summary>
        [DataMember(Name = "contentSize", EmitDefaultValue = false)]
        [Preserve]
        public long ContentSize { get; set; }

        /// <summary>
        /// Gets or Sets ContentUri
        /// </summary>
        [DataMember(Name = "contentUri", EmitDefaultValue = false)]
        [Preserve]
        public string ContentUri { get; set; }

        /// <summary>
        /// Gets or Sets EnvironmentId
        /// </summary>
        [DataMember(Name = "environmentId", EmitDefaultValue = false)]
        [Preserve]
        public string EnvironmentId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [Preserve]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets LastModified
        /// </summary>
        [DataMember(Name = "lastModified", EmitDefaultValue = false)]
        [Preserve]
        public DateTime LastModified { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        [Preserve]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets PreviousFile
        /// </summary>
        [DataMember(Name = "previousFile", EmitDefaultValue = true)]
        [Preserve]
        public FileWithStatePreviousFile PreviousFile { get; set; }

        /// <summary>
        /// Gets or Sets VariantTag
        /// </summary>
        [DataMember(Name = "variantTag", EmitDefaultValue = false)]
        [Preserve]
        public List<string> VariantTag { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileWithState" /> class.
        /// </summary>
        /// <param name="complete">complete.</param>
        /// <param name="contentSize">contentSize.</param>
        /// <param name="contentUri">contentUri.</param>
        /// <param name="environmentId">environmentId.</param>
        /// <param name="id">id.</param>
        /// <param name="lastModified">lastModified.</param>
        /// <param name="path">path.</param>
        /// <param name="previousFile">previousFile.</param>
        /// <param name="state">state.</param>
        /// <param name="type">type.</param>
        /// <param name="variantTag">variantTag.</param>
        [Preserve]
        public FileWithState(bool complete = default(bool), long contentSize = default(long), string contentUri = default(string), string environmentId = default(string), string id = default(string), DateTime lastModified = default(DateTime), string path = default(string), FileWithStatePreviousFile previousFile = default(FileWithStatePreviousFile), StateEnum? state = default(StateEnum?), ResourceType? type = default(ResourceType?), List<string> variantTag = default(List<string>))
        {
            this.Complete = complete;
            this.ContentSize = contentSize;
            this.ContentUri = contentUri;
            this.EnvironmentId = environmentId;
            this.Id = id;
            this.LastModified = lastModified;
            this.Path = path;
            this.PreviousFile = previousFile;
            this.State = state;
            this.Type = type;
            this.VariantTag = variantTag;
        }
    }

}
#endif