#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// Metadata
    /// </summary>
    [DataContract(Name = "metadata")]
    [Preserve]
    public partial class Metadata
    {
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        [Preserve]
        public ResourceType? Type { get; set; }
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [Preserve]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [DataMember(Name = "path", EmitDefaultValue = false)]
        [Preserve]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets ContentSize
        /// </summary>
        [DataMember(Name = "contentSize", EmitDefaultValue = false)]
        [Preserve]
        public long ContentSize { get; set; }

        /// <summary>
        /// Base64-encoded MD5 hash of the file content
        /// </summary>
        /// <value>Base64-encoded MD5 hash of the file content</value>
        [DataMember(Name = "contentHash", EmitDefaultValue = false)]
        [Preserve]
        public string ContentHash { get; set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        [Preserve]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets ContentUri
        /// </summary>
        [DataMember(Name = "contentUri", EmitDefaultValue = false)]
        [Preserve]
        public string ContentUri { get; set; }

        /// <summary>
        /// Gets or Sets Complete
        /// </summary>
        [DataMember(Name = "complete", EmitDefaultValue = true)]
        [Preserve]
        public bool Complete { get; set; }

        /// <summary>
        /// Gets or Sets VariantTag
        /// </summary>
        [DataMember(Name = "variantTag", EmitDefaultValue = false)]
        [Preserve]
        public List<string> VariantTag { get; set; }

        /// <summary>
        /// Gets or Sets _Metadata
        /// </summary>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        [Preserve]
        public Dictionary<string, ApiObject> _Metadata { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        [Preserve]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        [Preserve]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets DeletedAt
        /// </summary>
        [DataMember(Name = "deletedAt", EmitDefaultValue = false)]
        [Preserve]
        public DateTime DeletedAt { get; set; }

        /// <summary>
        /// Gets or Sets LastModifiedBy
        /// </summary>
        [DataMember(Name = "lastModifiedBy", EmitDefaultValue = false)]
        [Preserve]
        public string LastModifiedBy { get; set; }

        /// <summary>
        /// Gets or Sets LastModifiedByName
        /// </summary>
        [DataMember(Name = "lastModifiedByName", EmitDefaultValue = false)]
        [Preserve]
        public string LastModifiedByName { get; set; }

        /// <summary>
        /// Gets or Sets SignedUrl
        /// </summary>
        [DataMember(Name = "signedUrl", EmitDefaultValue = false)]
        [Preserve]
        public string SignedUrl { get; set; }

        /// <summary>
        /// Gets or Sets Schemas
        /// </summary>
        [DataMember(Name = "schemas", EmitDefaultValue = false)]
        [Preserve]
        public List<string> Schemas { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Metadata" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="path">path.</param>
        /// <param name="type">type.</param>
        /// <param name="contentSize">contentSize.</param>
        /// <param name="contentHash">Base64-encoded MD5 hash of the file content.</param>
        /// <param name="contentType">contentType.</param>
        /// <param name="contentUri">contentUri.</param>
        /// <param name="complete">complete.</param>
        /// <param name="variantTag">variantTag.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        /// <param name="deletedAt">deletedAt.</param>
        /// <param name="lastModifiedBy">lastModifiedBy.</param>
        /// <param name="lastModifiedByName">lastModifiedByName.</param>
        /// <param name="signedUrl">signedUrl.</param>
        /// <param name="schemas">schemas.</param>
        [Preserve]
        public Metadata(string id = default(string), string path = default(string), ResourceType? type = default(ResourceType?), long contentSize = default(long), string contentHash = default(string), string contentType = default(string), string contentUri = default(string), bool complete = default(bool), List<string> variantTag = default(List<string>), Dictionary<string, ApiObject> metadata = default(Dictionary<string, ApiObject>), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime), DateTime deletedAt = default(DateTime), string lastModifiedBy = default(string), string lastModifiedByName = default(string), string signedUrl = default(string), List<string> schemas = default(List<string>))
        {
            this.Id = id;
            this.Path = path;
            this.Type = type;
            this.ContentSize = contentSize;
            this.ContentHash = contentHash;
            this.ContentType = contentType;
            this.ContentUri = contentUri;
            this.Complete = complete;
            this.VariantTag = variantTag;
            this._Metadata = metadata;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.DeletedAt = deletedAt;
            this.LastModifiedBy = lastModifiedBy;
            this.LastModifiedByName = lastModifiedByName;
            this.SignedUrl = signedUrl;
            this.Schemas = schemas;
        }
    }

}
#endif