#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using UnityEngine.Scripting;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// ReleaseCompareSummary
    /// </summary>
    [DataContract(Name = "releaseCompareSummary")]
    [Preserve]
    internal partial class ReleaseCompareSummary
    {
        /// <summary>
        /// Gets or Sets Added
        /// </summary>
        [DataMember(Name = "added", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public long Added { get; set; }

        /// <summary>
        /// Gets or Sets Deleted
        /// </summary>
        [DataMember(Name = "deleted", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public long Deleted { get; set; }

        /// <summary>
        /// Gets or Sets Modified
        /// </summary>
        [DataMember(Name = "modified", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public long Modified { get; set; }

        /// <summary>
        /// Gets or Sets Unchanged
        /// </summary>
        [DataMember(Name = "unchanged", IsRequired = true, EmitDefaultValue = true)]
        [Preserve]
        public long Unchanged { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseCompareSummary" /> class.
        /// </summary>
        /// <param name="added">added (required).</param>
        /// <param name="deleted">deleted (required).</param>
        /// <param name="modified">modified (required).</param>
        /// <param name="unchanged">unchanged (required).</param>
        [Preserve]
        public ReleaseCompareSummary(long added = default(long), long deleted = default(long), long modified = default(long), long unchanged = default(long))
        {
            this.Added = added;
            this.Deleted = deleted;
            this.Modified = modified;
            this.Unchanged = unchanged;
        }
    }

}
#endif