//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.Scripting;
using UnityEngine.Purchasing.LiveContentAdapterService.Models;
using UnityEngine.Purchasing.LiveContentAdapterService.Scheduler;
using UnityEngine.Purchasing.LiveContentAdapterService.Http;
using Unity.Services.Authentication.Internal;

namespace UnityEngine.Purchasing.LiveContentAdapterService.Client
{
    internal static class JsonSerialization
    {
        public static byte[] Serialize<T>(T obj)
        {
            return Encoding.UTF8.GetBytes(SerializeToString(obj));
        }

        public static string SerializeToString<T>(T obj)
        {
            return IsolatedJsonConvert.SerializeObject(obj, new JsonSerializerSettings{ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore});
        }
    }

    /// <summary>
    /// ClientApiBaseRequest class
    /// </summary>
    [Preserve]
    internal class ClientApiBaseRequest
    {
        /// <summary>
        /// Helper function to add a provided key and value to the provided
        /// query params and to escape the values correctly if it is a URL.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="key">The key to be added.</param>
        /// <param name="value">The value to be added.</param>
        /// <returns>Returns a `List/<string/>` with the `key` and `value` added to the provided `queryParams`.</returns>
        [Preserve]
        public List<string> AddParamsToQueryParams(List<string> queryParams, string key, string value)
        {
            key = UnityWebRequest.EscapeURL(key);
            value = UnityWebRequest.EscapeURL(value);
            queryParams.Add($"{key}={value}");

            return queryParams;
        }

        /// <summary>
        /// Helper function to add a provided key and list of values to the
        /// provided query params and to escape the values correctly if it is a
        /// URL.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="key">The key to be added.</param>
        /// <param name="values">List of values to be added.</param>
        /// <param name="style">string for defining the style, currently unused.</param>
        /// <param name="explode">True if query params should be escaped and added separately.</param>
        /// <returns>Returns a `List/<string/>`</returns>
        [Preserve]
        public List<string> AddParamsToQueryParams(List<string> queryParams, string key, List<string> values, string style, bool explode)
        {
            if (explode)
            {
                foreach(var value in values)
                {
                    string escapedValue = UnityWebRequest.EscapeURL(value);
                    queryParams.Add($"{UnityWebRequest.EscapeURL(key)}={escapedValue}");
                }
            }
            else
            {
                string paramString = $"{UnityWebRequest.EscapeURL(key)}=";
                foreach(var value in values)
                {
                    paramString += UnityWebRequest.EscapeURL(value) + ",";
                }
                paramString = paramString.Remove(paramString.Length - 1);
                queryParams.Add(paramString);
            }

            return queryParams;
        }

        /// <summary>
        /// Helper function to add a provided map of keys and values, representing a model, to the
        /// provided query params.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="modelVars">A `Dictionary` representing the vars of the model</param>
        /// <returns>Returns a `List/<string/>`</returns>
        [Preserve]
        public List<string> AddParamsToQueryParams(List<string> queryParams, Dictionary<string, string> modelVars)
        {
            foreach(var key in modelVars.Keys)
            {
                string escapedValue = UnityWebRequest.EscapeURL(modelVars[key]);
                queryParams.Add($"{UnityWebRequest.EscapeURL(key)}={escapedValue}");
            }

            return queryParams;
        }

        /// <summary>
        /// Helper function to add a provided key and value to the provided
        /// query params and to escape the values correctly if it is a URL.
        /// </summary>
        /// <param name="queryParams">A `List/<string/>` of the query parameters.</param>
        /// <param name="key">The key to be added.</param>
        /// <typeparam name="T">The type of the value to be added.</typeparam>
        /// <param name="value">The value to be added.</param>
        /// <returns>Returns a `List/<string/>`</returns>
        [Preserve]
        public List<string> AddParamsToQueryParams<T>(List<string> queryParams, string key, T value)
        {
            if (queryParams == null)
            {
                queryParams = new List<string>();
            }

            key = UnityWebRequest.EscapeURL(key);
            string valueString = UnityWebRequest.EscapeURL(value.ToString());
            queryParams.Add($"{key}={valueString}");
            return queryParams;
        }

        /// <summary>
        /// Constructs a string representing an array path parameter.
        /// </summary>
        /// <param name="pathParam">The list of values to convert to string.</param>
        /// <returns>String representing the param.</returns>
        [Preserve]
        public string GetPathParamString(List<string> pathParam)
        {
            string paramString = "";
            foreach(var value in pathParam)
            {
                paramString += UnityWebRequest.EscapeURL(value) + ",";
            }
            paramString = paramString.Remove(paramString.Length - 1);
            return paramString;
        }

        /// <summary>
        /// Constructs the body of the request based on IO stream.
        /// </summary>
        /// <param name="stream">The IO stream to use.</param>
        /// <returns>Byte array representing the body.</returns>
        public byte[] ConstructBody(System.IO.Stream stream)
        {
            if (stream != null)
            {
                using (System.IO.MemoryStream ms = new System.IO.MemoryStream())
                {
                    stream.CopyTo(ms);
                    return ms.ToArray();
                }
            }
            return null;
        }

        /// <summary>
        /// Construct the request body based on string value.
        /// </summary>
        /// <param name="s">The input body.</param>
        /// <returns>Byte array representing the body.</returns>
        public byte[] ConstructBody(string s)
        {
            return System.Text.Encoding.UTF8.GetBytes(s);
        }

        /// <summary>
        /// Construct request body based on generic object.
        /// </summary>
        /// <param name="o">The object to use.</param>
        /// <returns>Byte array representing the body.</returns>
        public byte[] ConstructBody(object o)
        {
            return JsonSerialization.Serialize(o);
        }

        /// <summary>
        /// Generate an accept header.
        /// </summary>
        /// <param name="accepts">list of accepts objects.</param>
        /// <returns>The generated accept header.</returns>
        public string GenerateAcceptHeader(string[] accepts)
        {
            if (accepts.Length == 0)
            {
                return null;
            }
            for (int i = 0; i < accepts.Length; ++i)
            {
                if (string.Equals(accepts[i], "application/json", System.StringComparison.OrdinalIgnoreCase))
                {
                    return "application/json";
                }
            }
            return string.Join(", ", accepts);
        }

        private static readonly Regex JsonRegex = new Regex(@"application\/json(;\s)?((charset=utf8|q=[0-1]\.\d)(\s)?)*");

        /// <summary>
        /// Generate Content Type Header.
        /// </summary>
        /// <param name="contentTypes">The content types.</param>
        /// <returns>The Content Type Header.</returns>
        public string GenerateContentTypeHeader(string[] contentTypes)
        {
            if (contentTypes.Length == 0)
            {
                return null;
            }

            for(int i = 0; i < contentTypes.Length; ++i)
            {
                if (!string.IsNullOrWhiteSpace(contentTypes[i]) && JsonRegex.IsMatch(contentTypes[i]))
                {
                    return contentTypes[i];
                }
            }
            return contentTypes[0];
        }

        /// <summary>
        /// Generate multipart form file section.
        /// </summary>
        /// <param name="paramName">The parameter name.</param>
        /// <param name="stream">The file stream to use.</param>
        /// <param name="contentType">The content type.</param>
        /// <returns>Returns a multipart form section.</returns>
        public IMultipartFormSection GenerateMultipartFormFileSection(string paramName, System.IO.FileStream stream, string contentType)
        {
            return new MultipartFormFileSection(paramName, ConstructBody(stream), GetFileName(stream.Name), contentType);
        }

        /// <summary>
        /// Generate multipart form file section.
        /// </summary>
        /// <param name="paramName">The parameter name.</param>
        /// <param name="stream">The IO stream to use.</param>
        /// <param name="contentType">The content type.</param>
        /// <returns>Returns a multipart form section.</returns>
        public IMultipartFormSection GenerateMultipartFormFileSection(string paramName, System.IO.Stream stream, string contentType)
        {
            return new MultipartFormFileSection(paramName, ConstructBody(stream), Guid.NewGuid().ToString(), contentType);
        }

        private string GetFileName(string filePath)
        {
            return System.IO.Path.GetFileName(filePath);
        }
    }

    /// <summary>
    /// GetPlayerConfigContentRequest
    /// Get config content
    /// </summary>
    [Preserve]
    internal class GetPlayerConfigContentRequest : ClientApiBaseRequest
    {
        /// <summary>Accessor for projectId </summary>
        [Preserve]
        public string ProjectId { get; }
        string PathAndQueryParams;

        /// <summary>
        /// GetPlayerConfigContent Request Object.
        /// Get config content
        /// </summary>
        /// <param name="projectId">Project ID</param>
        [Preserve]
        public GetPlayerConfigContentRequest(string projectId)
        {
            ProjectId = projectId;

            PathAndQueryParams = $"/projects/{projectId}/configs/content/(.+)$";


        }

        /// <summary>
        /// Helper function for constructing URL from request base path and
        /// query params.
        /// </summary>
        /// <param name="requestBasePath"></param>
        /// <returns></returns>
        public string ConstructUrl(string requestBasePath)
        {
            return requestBasePath + PathAndQueryParams;
        }

        /// <summary>
        /// Helper for constructing the request body.
        /// </summary>
        /// <returns>A list of IMultipartFormSection representing the request body.</returns>
        public byte[] ConstructBody()
        {
            return null;
        }

        /// <summary>
        /// Helper function for constructing the headers.
        /// </summary>
        /// <param name="accessToken">The auth access token to use.</param>
        /// <param name="operationConfiguration">The operation configuration to use.</param>
        /// <returns>A dictionary representing the request headers.</returns>
        public Dictionary<string, string> ConstructHeaders(IAccessToken accessToken,
            Configuration operationConfiguration = null)
        {
            var headers = new Dictionary<string, string>();

            // Analytics headers
            headers.Add("Unity-Client-Version", Application.unityVersion);
            headers.Add("Unity-Client-Mode", Scheduler.EngineStateHelper.IsPlaying ? "play" : "edit");

            string[] contentTypes = {
            };

            string[] accepts = {
                "application/json"
            };

            var acceptHeader = GenerateAcceptHeader(accepts);
            if (!string.IsNullOrEmpty(acceptHeader))
            {
                headers.Add("Accept", acceptHeader);
            }
            var httpMethod = "GET";
            var contentTypeHeader = GenerateContentTypeHeader(contentTypes);
            if (!string.IsNullOrEmpty(contentTypeHeader))
            {
                headers.Add("Content-Type", contentTypeHeader);
            }
            else if (httpMethod == "POST" || httpMethod == "PATCH")
            {
                headers.Add("Content-Type", "application/json");
            }


            // We also check if there are headers that are defined as part of
            // the request configuration.
            if (operationConfiguration != null && operationConfiguration.Headers != null)
            {
                foreach (var pair in operationConfiguration.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }

            return headers;
        }
    }
    /// <summary>
    /// GetPlayerConfigsRequest
    /// Get player configs
    /// </summary>
    [Preserve]
    internal class GetPlayerConfigsRequest : ClientApiBaseRequest
    {
        /// <summary>Accessor for projectId </summary>
        [Preserve]
        public string ProjectId { get; }
        /// <summary>Accessor for page </summary>
        [Preserve]
        public long? Page { get; }
        /// <summary>Accessor for limit </summary>
        [Preserve]
        public long? Limit { get; }
        /// <summary>Accessor for path </summary>
        [Preserve]
        public string Path { get; }
        /// <summary>Accessor for schema </summary>
        [Preserve]
        public string Schema { get; }
        /// <summary>Accessor for next </summary>
        [Preserve]
        public string Next { get; }
        /// <summary>Accessor for after </summary>
        [Preserve]
        public string After { get; }
        /// <summary>Accessor for start </summary>
        [Preserve]
        public bool? Start { get; }
        /// <summary>Accessor for metadata </summary>
        [Preserve]
        public string Metadata { get; }
        string PathAndQueryParams;

        /// <summary>
        /// GetPlayerConfigs Request Object.
        /// Get player configs
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="page">Current Page. Deprecated: use the `next` cursor instead for efficient pagination.</param>
        /// <param name="limit">Items Per Page</param>
        /// <param name="path">Path</param>
        /// <param name="schema">URI-escaped Schema identifier</param>
        /// <param name="next">Opaque cursor token returned in the `X-Next` response header from a previous request. When provided, returns the next page of results. Takes precedence over `after` and `start`.</param>
        /// <param name="after">Path-based cursor - returns configs listed alphabetically after this config path</param>
        /// <param name="start">Path-based cursor - Start from the alphabetically first config path</param>
        /// <param name="metadata">AIP-160 filter expression scoped to the metadata object. Field paths are relative to the metadata object — do not include a \"metadata.\" prefix. Supported operators: = != < <= > >= : (has/contains) AND OR NOT. Wildcards: use * in string values for glob matching (e.g. \"io*\" matches \"ios\"). Examples:   ?metadata=platform=\"ios\"   ?metadata=platform=\"ios\" AND version>3   ?metadata=platform=\"ios\" OR platform=\"android\"   ?metadata=NOT platform=\"web\"   ?metadata=tags:\"mobile\"   ?metadata=version:*</param>
        [Preserve]
        public GetPlayerConfigsRequest(string projectId, long? page = default(long?), long? limit = 10, string path = default(string), string schema = default(string), string next = default(string), string after = default(string), bool? start = default(bool?), string metadata = default(string))
        {
            ProjectId = projectId;

            Page = page;
            Limit = limit;
            Path = path;
            Schema = schema;
            Next = next;
            After = after;
            Start = start;
            Metadata = metadata;
            PathAndQueryParams = $"/projects/{projectId}/configs/info";

            List<string> queryParams = new List<string>();

            var pageStringValue = Page.ToString();
            if (!string.IsNullOrEmpty(pageStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "page", pageStringValue);
            }
            var limitStringValue = Limit.ToString();
            if (!string.IsNullOrEmpty(limitStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "limit", limitStringValue);
            }
            if(!string.IsNullOrEmpty(Path))
            {
                queryParams = AddParamsToQueryParams(queryParams, "path", Path);
            }
            if(!string.IsNullOrEmpty(Schema))
            {
                queryParams = AddParamsToQueryParams(queryParams, "schema", Schema);
            }
            if(!string.IsNullOrEmpty(Next))
            {
                queryParams = AddParamsToQueryParams(queryParams, "next", Next);
            }
            if(!string.IsNullOrEmpty(After))
            {
                queryParams = AddParamsToQueryParams(queryParams, "after", After);
            }
            var startStringValue = Start.ToString();
            if (!string.IsNullOrEmpty(startStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "start", startStringValue);
            }
            if(!string.IsNullOrEmpty(Metadata))
            {
                queryParams = AddParamsToQueryParams(queryParams, "metadata", Metadata);
            }
            if (queryParams.Count > 0)
            {
                PathAndQueryParams = $"{PathAndQueryParams}?{string.Join("&", queryParams)}";
            }
        }

        /// <summary>
        /// Helper function for constructing URL from request base path and
        /// query params.
        /// </summary>
        /// <param name="requestBasePath"></param>
        /// <returns></returns>
        public string ConstructUrl(string requestBasePath)
        {
            return requestBasePath + PathAndQueryParams;
        }

        /// <summary>
        /// Helper for constructing the request body.
        /// </summary>
        /// <returns>A list of IMultipartFormSection representing the request body.</returns>
        public byte[] ConstructBody()
        {
            return null;
        }

        /// <summary>
        /// Helper function for constructing the headers.
        /// </summary>
        /// <param name="accessToken">The auth access token to use.</param>
        /// <param name="operationConfiguration">The operation configuration to use.</param>
        /// <returns>A dictionary representing the request headers.</returns>
        public Dictionary<string, string> ConstructHeaders(IAccessToken accessToken,
            Configuration operationConfiguration = null)
        {
            var headers = new Dictionary<string, string>();

            // Analytics headers
            headers.Add("Unity-Client-Version", Application.unityVersion);
            headers.Add("Unity-Client-Mode", Scheduler.EngineStateHelper.IsPlaying ? "play" : "edit");

            string[] contentTypes = {
            };

            string[] accepts = {
                "application/json"
            };

            var acceptHeader = GenerateAcceptHeader(accepts);
            if (!string.IsNullOrEmpty(acceptHeader))
            {
                headers.Add("Accept", acceptHeader);
            }
            var httpMethod = "GET";
            var contentTypeHeader = GenerateContentTypeHeader(contentTypes);
            if (!string.IsNullOrEmpty(contentTypeHeader))
            {
                headers.Add("Content-Type", contentTypeHeader);
            }
            else if (httpMethod == "POST" || httpMethod == "PATCH")
            {
                headers.Add("Content-Type", "application/json");
            }


            // We also check if there are headers that are defined as part of
            // the request configuration.
            if (operationConfiguration != null && operationConfiguration.Headers != null)
            {
                foreach (var pair in operationConfiguration.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }

            return headers;
        }
    }
    /// <summary>
    /// GetPlayerConfigsContentRequest
    /// Get player configs with inline content
    /// </summary>
    [Preserve]
    internal class GetPlayerConfigsContentRequest : ClientApiBaseRequest
    {
        /// <summary>Accessor for projectId </summary>
        [Preserve]
        public string ProjectId { get; }
        /// <summary>Accessor for page </summary>
        [Preserve]
        public long? Page { get; }
        /// <summary>Accessor for limit </summary>
        [Preserve]
        public long? Limit { get; }
        /// <summary>Accessor for path </summary>
        [Preserve]
        public string Path { get; }
        /// <summary>Accessor for schema </summary>
        [Preserve]
        public string Schema { get; }
        /// <summary>Accessor for schemaVersion </summary>
        [Preserve]
        public string SchemaVersion { get; }
        /// <summary>Accessor for next </summary>
        [Preserve]
        public string Next { get; }
        /// <summary>Accessor for after </summary>
        [Preserve]
        public string After { get; }
        /// <summary>Accessor for start </summary>
        [Preserve]
        public bool? Start { get; }
        /// <summary>Accessor for metadata </summary>
        [Preserve]
        public string Metadata { get; }
        string PathAndQueryParams;

        /// <summary>
        /// GetPlayerConfigsContent Request Object.
        /// Get player configs with inline content
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="page">Current Page. Deprecated: use the `next` cursor instead for efficient pagination.</param>
        /// <param name="limit">Items Per Page</param>
        /// <param name="path">Path</param>
        /// <param name="schema">URI-escaped Schema identifier</param>
        /// <param name="schemaVersion">TEMPORARY DESCRIPTION: schema version filter. Examples: \"1.*\", \">=1.1.0\", \"1.0.0\", \">=1.0.0,<2.0.0\".</param>
        /// <param name="next">Opaque cursor token returned in the `X-Next` response header from a previous request. When provided, returns the next page of results. Takes precedence over `after` and `start`.</param>
        /// <param name="after">Path-based cursor - returns configs listed alphabetically after this config path</param>
        /// <param name="start">Path-based cursor - Start from the alphabetically first config path</param>
        /// <param name="metadata">AIP-160 filter expression scoped to the metadata object. Field paths are relative to the metadata object — do not include a \"metadata.\" prefix. Supported operators: = != < <= > >= : (has/contains) AND OR NOT. Wildcards: use * in string values for glob matching (e.g. \"io*\" matches \"ios\"). Examples:   ?metadata=platform=\"ios\"   ?metadata=platform=\"ios\" AND version>3   ?metadata=platform=\"ios\" OR platform=\"android\"   ?metadata=NOT platform=\"web\"   ?metadata=tags:\"mobile\"   ?metadata=version:*</param>
        [Preserve]
        public GetPlayerConfigsContentRequest(string projectId, long? page = default(long?), long? limit = 10, string path = default(string), string schema = default(string), string schemaVersion = default(string), string next = default(string), string after = default(string), bool? start = default(bool?), string metadata = default(string))
        {
            ProjectId = projectId;

            Page = page;
            Limit = limit;
            Path = path;
            Schema = schema;
            SchemaVersion = schemaVersion;
            Next = next;
            After = after;
            Start = start;
            Metadata = metadata;
            PathAndQueryParams = $"/projects/{projectId}/configs/content";

            List<string> queryParams = new List<string>();

            var pageStringValue = Page.ToString();

            if (!string.IsNullOrEmpty(pageStringValue))

            {

                queryParams = AddParamsToQueryParams(queryParams, "page", pageStringValue);

            }
            var limitStringValue = Limit.ToString();
            if (!string.IsNullOrEmpty(limitStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "limit", limitStringValue);
            }
            if(!string.IsNullOrEmpty(Path))
            {
                queryParams = AddParamsToQueryParams(queryParams, "path", Path);
            }
            if(!string.IsNullOrEmpty(Schema))
            {
                queryParams = AddParamsToQueryParams(queryParams, "schema", Schema);
            }
            if(!string.IsNullOrEmpty(SchemaVersion))
            {
                queryParams = AddParamsToQueryParams(queryParams, "schemaVersion", SchemaVersion);
            }
            if(!string.IsNullOrEmpty(Next))
            {
                queryParams = AddParamsToQueryParams(queryParams, "next", Next);
            }
            if(!string.IsNullOrEmpty(After))
            {
                queryParams = AddParamsToQueryParams(queryParams, "after", After);
            }
            var startStringValue = Start.ToString();
            if (!string.IsNullOrEmpty(startStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "start", startStringValue);
            }
            if(!string.IsNullOrEmpty(Metadata))
            {
                queryParams = AddParamsToQueryParams(queryParams, "metadata", Metadata);
            }
            if (queryParams.Count > 0)
            {
                PathAndQueryParams = $"{PathAndQueryParams}?{string.Join("&", queryParams)}";
            }
        }

        /// <summary>
        /// Helper function for constructing URL from request base path and
        /// query params.
        /// </summary>
        /// <param name="requestBasePath"></param>
        /// <returns></returns>
        public string ConstructUrl(string requestBasePath)
        {
            return requestBasePath + PathAndQueryParams;
        }

        /// <summary>
        /// Helper for constructing the request body.
        /// </summary>
        /// <returns>A list of IMultipartFormSection representing the request body.</returns>
        public byte[] ConstructBody()
        {
            return null;
        }

        /// <summary>
        /// Helper function for constructing the headers.
        /// </summary>
        /// <param name="accessToken">The auth access token to use.</param>
        /// <param name="operationConfiguration">The operation configuration to use.</param>
        /// <returns>A dictionary representing the request headers.</returns>
        public Dictionary<string, string> ConstructHeaders(IAccessToken accessToken,
            Configuration operationConfiguration = null)
        {
            var headers = new Dictionary<string, string>();
            if(!string.IsNullOrEmpty(accessToken.AccessToken))
            {
                headers.Add("authorization", "Bearer " + accessToken.AccessToken);
            }

            // Analytics headers
            headers.Add("Unity-Client-Version", Application.unityVersion);
            headers.Add("Unity-Client-Mode", Scheduler.EngineStateHelper.IsPlaying ? "play" : "edit");

            string[] contentTypes = {
            };

            string[] accepts = {
                "application/json"
            };

            var acceptHeader = GenerateAcceptHeader(accepts);
            if (!string.IsNullOrEmpty(acceptHeader))
            {
                headers.Add("Accept", acceptHeader);
            }
            var httpMethod = "GET";
            var contentTypeHeader = GenerateContentTypeHeader(contentTypes);
            if (!string.IsNullOrEmpty(contentTypeHeader))
            {
                headers.Add("Content-Type", contentTypeHeader);
            }
            else if (httpMethod == "POST" || httpMethod == "PATCH")
            {
                headers.Add("Content-Type", "application/json");
            }


            // We also check if there are headers that are defined as part of
            // the request configuration.
            if (operationConfiguration != null && operationConfiguration.Headers != null)
            {
                foreach (var pair in operationConfiguration.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }

            return headers;
        }
    }
    /// <summary>
    /// GetPlayerFileContentRequest
    /// Get file content
    /// </summary>
    [Preserve]
    internal class GetPlayerFileContentRequest : ClientApiBaseRequest
    {
        /// <summary>Accessor for projectId </summary>
        [Preserve]
        public string ProjectId { get; }
        string PathAndQueryParams;

        /// <summary>
        /// GetPlayerFileContent Request Object.
        /// Get file content
        /// </summary>
        /// <param name="projectId">Project ID</param>
        [Preserve]
        public GetPlayerFileContentRequest(string projectId)
        {
            ProjectId = projectId;

            PathAndQueryParams = $"/projects/{projectId}/files/content/(.+)$";


        }

        /// <summary>
        /// Helper function for constructing URL from request base path and
        /// query params.
        /// </summary>
        /// <param name="requestBasePath"></param>
        /// <returns></returns>
        public string ConstructUrl(string requestBasePath)
        {
            return requestBasePath + PathAndQueryParams;
        }

        /// <summary>
        /// Helper for constructing the request body.
        /// </summary>
        /// <returns>A list of IMultipartFormSection representing the request body.</returns>
        public byte[] ConstructBody()
        {
            return null;
        }

        /// <summary>
        /// Helper function for constructing the headers.
        /// </summary>
        /// <param name="accessToken">The auth access token to use.</param>
        /// <param name="operationConfiguration">The operation configuration to use.</param>
        /// <returns>A dictionary representing the request headers.</returns>
        public Dictionary<string, string> ConstructHeaders(IAccessToken accessToken,
            Configuration operationConfiguration = null)
        {
            var headers = new Dictionary<string, string>();

            // Analytics headers
            headers.Add("Unity-Client-Version", Application.unityVersion);
            headers.Add("Unity-Client-Mode", Scheduler.EngineStateHelper.IsPlaying ? "play" : "edit");

            string[] contentTypes = {
            };

            string[] accepts = {
            };

            var acceptHeader = GenerateAcceptHeader(accepts);
            if (!string.IsNullOrEmpty(acceptHeader))
            {
                headers.Add("Accept", acceptHeader);
            }
            var httpMethod = "GET";
            var contentTypeHeader = GenerateContentTypeHeader(contentTypes);
            if (!string.IsNullOrEmpty(contentTypeHeader))
            {
                headers.Add("Content-Type", contentTypeHeader);
            }
            else if (httpMethod == "POST" || httpMethod == "PATCH")
            {
                headers.Add("Content-Type", "application/json");
            }


            // We also check if there are headers that are defined as part of
            // the request configuration.
            if (operationConfiguration != null && operationConfiguration.Headers != null)
            {
                foreach (var pair in operationConfiguration.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }

            return headers;
        }
    }
    /// <summary>
    /// GetPlayerFilesRequest
    /// Get player files
    /// </summary>
    [Preserve]
    internal class GetPlayerFilesRequest : ClientApiBaseRequest
    {
        /// <summary>Accessor for projectId </summary>
        [Preserve]
        public string ProjectId { get; }
        /// <summary>Accessor for page </summary>
        [Preserve]
        public long? Page { get; }
        /// <summary>Accessor for limit </summary>
        [Preserve]
        public long? Limit { get; }
        /// <summary>Accessor for path </summary>
        [Preserve]
        public string Path { get; }
        /// <summary>Accessor for next </summary>
        [Preserve]
        public string Next { get; }
        /// <summary>Accessor for after </summary>
        [Preserve]
        public string After { get; }
        /// <summary>Accessor for start </summary>
        [Preserve]
        public bool? Start { get; }
        /// <summary>Accessor for metadata </summary>
        [Preserve]
        public string Metadata { get; }
        string PathAndQueryParams;

        /// <summary>
        /// GetPlayerFiles Request Object.
        /// Get player files
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="page">Current Page. Deprecated: use the `next` cursor instead for efficient pagination.</param>
        /// <param name="limit">Items Per Page</param>
        /// <param name="path">Path</param>
        /// <param name="next">Opaque cursor token returned in the `X-Next` response header from a previous request.  When provided, returns the next page of results. Takes precedence over `after` and `start`.</param>
        /// <param name="after">Path-based cursor - returns files listed alphabetically after this file path</param>
        /// <param name="start">Path-based cursor - Start from the alphabetically first file path</param>
        /// <param name="metadata">AIP-160 filter expression scoped to the metadata object. Field paths are relative to the metadata object — do not include a \"metadata.\" prefix. Supported operators: = != < <= > >= : (has/contains) AND OR NOT. Wildcards: use * in string values for glob matching (e.g. \"io*\" matches \"ios\"). Examples:   ?metadata=platform=\"ios\"   ?metadata=platform=\"ios\" AND version>3   ?metadata=platform=\"ios\" OR platform=\"android\"   ?metadata=NOT platform=\"web\"   ?metadata=tags:\"mobile\"   ?metadata=version:*</param>
        [Preserve]
        public GetPlayerFilesRequest(string projectId, long? page = default(long?), long? limit = 10, string path = default(string), string next = default(string), string after = default(string), bool? start = default(bool?), string metadata = default(string))
        {
            ProjectId = projectId;

            Page = page;
            Limit = limit;
            Path = path;
            Next = next;
            After = after;
            Start = start;
            Metadata = metadata;
            PathAndQueryParams = $"/projects/{projectId}/files/info";

            List<string> queryParams = new List<string>();

            var pageStringValue = Page.ToString();

            if (!string.IsNullOrEmpty(pageStringValue))

            {

                queryParams = AddParamsToQueryParams(queryParams, "page", pageStringValue);

            }
            var limitStringValue = Limit.ToString();
            if (!string.IsNullOrEmpty(limitStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "limit", limitStringValue);
            }
            if(!string.IsNullOrEmpty(Path))
            {
                queryParams = AddParamsToQueryParams(queryParams, "path", Path);
            }
            if(!string.IsNullOrEmpty(Next))
            {
                queryParams = AddParamsToQueryParams(queryParams, "next", Next);
            }
            if(!string.IsNullOrEmpty(After))
            {
                queryParams = AddParamsToQueryParams(queryParams, "after", After);
            }
            var startStringValue = Start.ToString();
            if (!string.IsNullOrEmpty(startStringValue))
            {
                queryParams = AddParamsToQueryParams(queryParams, "start", startStringValue);
            }
            if(!string.IsNullOrEmpty(Metadata))
            {
                queryParams = AddParamsToQueryParams(queryParams, "metadata", Metadata);
            }
            if (queryParams.Count > 0)
            {
                PathAndQueryParams = $"{PathAndQueryParams}?{string.Join("&", queryParams)}";
            }
        }

        /// <summary>
        /// Helper function for constructing URL from request base path and
        /// query params.
        /// </summary>
        /// <param name="requestBasePath"></param>
        /// <returns></returns>
        public string ConstructUrl(string requestBasePath)
        {
            return requestBasePath + PathAndQueryParams;
        }

        /// <summary>
        /// Helper for constructing the request body.
        /// </summary>
        /// <returns>A list of IMultipartFormSection representing the request body.</returns>
        public byte[] ConstructBody()
        {
            return null;
        }

        /// <summary>
        /// Helper function for constructing the headers.
        /// </summary>
        /// <param name="accessToken">The auth access token to use.</param>
        /// <param name="operationConfiguration">The operation configuration to use.</param>
        /// <returns>A dictionary representing the request headers.</returns>
        public Dictionary<string, string> ConstructHeaders(IAccessToken accessToken,
            Configuration operationConfiguration = null)
        {
            var headers = new Dictionary<string, string>();

            // Analytics headers
            headers.Add("Unity-Client-Version", Application.unityVersion);
            headers.Add("Unity-Client-Mode", Scheduler.EngineStateHelper.IsPlaying ? "play" : "edit");

            string[] contentTypes = {
            };

            string[] accepts = {
                "application/json"
            };

            var acceptHeader = GenerateAcceptHeader(accepts);
            if (!string.IsNullOrEmpty(acceptHeader))
            {
                headers.Add("Accept", acceptHeader);
            }
            var httpMethod = "GET";
            var contentTypeHeader = GenerateContentTypeHeader(contentTypes);
            if (!string.IsNullOrEmpty(contentTypeHeader))
            {
                headers.Add("Content-Type", contentTypeHeader);
            }
            else if (httpMethod == "POST" || httpMethod == "PATCH")
            {
                headers.Add("Content-Type", "application/json");
            }


            // We also check if there are headers that are defined as part of
            // the request configuration.
            if (operationConfiguration != null && operationConfiguration.Headers != null)
            {
                foreach (var pair in operationConfiguration.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }

            return headers;
        }
    }
}
