//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using UnityEngine.Purchasing.LiveContentAdapterService.Models;
using UnityEngine.Purchasing.LiveContentAdapterService.Http;
using Unity.Services.Authentication.Internal;
using UnityEngine.Purchasing.LiveContentAdapterService.Client;

namespace UnityEngine.Purchasing.LiveContentAdapterService.Apis.Client
{
    /// <summary>
    /// Interface for the ClientApiClient
    /// </summary>
    internal interface IClientApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Get config content.
            /// </summary>
            /// <param name="request">Request object for GetPlayerConfigContent.</param>
            /// <param name="operationConfiguration">Configuration for GetPlayerConfigContent.</param>
            /// <returns>Task for a Response object containing status code, headers, and Dictionary&lt;string, IDeserializable&gt; object.</returns>
            /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<Dictionary<string, IDeserializable>>> GetPlayerConfigContentAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerConfigContentRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Get player configs.
            /// </summary>
            /// <param name="request">Request object for GetPlayerConfigs.</param>
            /// <param name="operationConfiguration">Configuration for GetPlayerConfigs.</param>
            /// <returns>Task for a Response object containing status code, headers, and List&lt;ClientFile&gt; object.</returns>
            /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<List<ClientFile>>> GetPlayerConfigsAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerConfigsRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Get player configs with inline content.
            /// </summary>
            /// <param name="request">Request object for GetPlayerConfigsContent.</param>
            /// <param name="operationConfiguration">Configuration for GetPlayerConfigsContent.</param>
            /// <returns>Task for a Response object containing status code, headers, and List&lt;ClientFileWithContent&gt; object.</returns>
            /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<List<ClientFileWithContent>>> GetPlayerConfigsContentAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerConfigsContentRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Get file content.
            /// </summary>
            /// <param name="request">Request object for GetPlayerFileContent.</param>
            /// <param name="operationConfiguration">Configuration for GetPlayerFileContent.</param>
            /// <returns>Task for a Response object containing status code, headers.</returns>
            /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response> GetPlayerFileContentAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerFileContentRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Get player files.
            /// </summary>
            /// <param name="request">Request object for GetPlayerFiles.</param>
            /// <param name="operationConfiguration">Configuration for GetPlayerFiles.</param>
            /// <returns>Task for a Response object containing status code, headers, and List&lt;ClientFile&gt; object.</returns>
            /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<List<ClientFile>>> GetPlayerFilesAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerFilesRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IClientApiClient"/>
    internal class ClientApiClient : BaseApiClient, IClientApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("https://services.api.unity.com/live-content/client/v1", 10, 4, null);
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// ClientApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for ClientApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> ClientApiClient Configuration object.</param>
        public ClientApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Get config content.
        /// </summary>
        /// <param name="request">Request object for GetPlayerConfigContent.</param>
        /// <param name="operationConfiguration">Configuration for GetPlayerConfigContent.</param>
        /// <returns>Task for a Response object containing status code, headers, and Dictionary&lt;string, object&gt; object.</returns>
        /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<Dictionary<string, IDeserializable>>> GetPlayerConfigContentAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerConfigContentRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(Dictionary<string, IDeserializable>)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<Dictionary<string, IDeserializable>>(response, statusCodeToTypeMap);
            return new Response<Dictionary<string, IDeserializable>>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Get player configs.
        /// </summary>
        /// <param name="request">Request object for GetPlayerConfigs.</param>
        /// <param name="operationConfiguration">Configuration for GetPlayerConfigs.</param>
        /// <returns>Task for a Response object containing status code, headers, and List&lt;ClientFile&gt; object.</returns>
        /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<List<ClientFile>>> GetPlayerConfigsAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerConfigsRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(List<ClientFile>)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<List<ClientFile>>(response, statusCodeToTypeMap);
            return new Response<List<ClientFile>>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Get player configs with inline content.
        /// </summary>
        /// <param name="request">Request object for GetPlayerConfigsContent.</param>
        /// <param name="operationConfiguration">Configuration for GetPlayerConfigsContent.</param>
        /// <returns>Task for a Response object containing status code, headers, and List&lt;ClientFileWithContent&gt; object.</returns>
        /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<List<ClientFileWithContent>>> GetPlayerConfigsContentAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerConfigsContentRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(List<ClientFileWithContent>)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<List<ClientFileWithContent>>(response, statusCodeToTypeMap);
            return new Response<List<ClientFileWithContent>>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Get file content.
        /// </summary>
        /// <param name="request">Request object for GetPlayerFileContent.</param>
        /// <param name="operationConfiguration">Configuration for GetPlayerFileContent.</param>
        /// <returns>Task for a Response object containing status code, headers.</returns>
        /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response> GetPlayerFileContentAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerFileContentRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"307",  null } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            ResponseHandler.HandleAsyncResponse(response, statusCodeToTypeMap);
            return new Response(response);
        }


        /// <summary>
        /// Async Operation.
        /// Get player files.
        /// </summary>
        /// <param name="request">Request object for GetPlayerFiles.</param>
        /// <param name="operationConfiguration">Configuration for GetPlayerFiles.</param>
        /// <returns>Task for a Response object containing status code, headers, and List&lt;ClientFile&gt; object.</returns>
        /// <exception cref="UnityEngine.Purchasing.LiveContentAdapterService.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<List<ClientFile>>> GetPlayerFilesAsync(UnityEngine.Purchasing.LiveContentAdapterService.Client.GetPlayerFilesRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(List<ClientFile>)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("GET",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<List<ClientFile>>(response, statusCodeToTypeMap);
            return new Response<List<ClientFile>>(response, handledResponse);
        }

    }
}
