//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using UnityEngine.Purchasing.TransactionVerifier.Apis.Apple;
using UnityEngine.Purchasing.TransactionVerifier.Apis.Google;


namespace UnityEngine.Purchasing.TransactionVerifier
{
    /// <summary>
    /// TransactionVerifierService
    /// </summary>
    internal static class TransactionVerifierService
    {
        /// <summary>
        /// The static instance of TransactionVerifierService.
        /// </summary>
        public static ITransactionVerifierService Instance { get; internal set; }
    }

    /// <summary> Interface for TransactionVerifierService</summary>
    internal interface ITransactionVerifierService
    {

        /// <summary> Accessor for AppleApi methods.</summary>
        IAppleApiClient AppleApi { get; set; }

        /// <summary> Accessor for GoogleApi methods.</summary>
        IGoogleApiClient GoogleApi { get; set; }


        /// <summary> Configuration properties for the service.</summary>
        Configuration Configuration { get; set; }
    }
}
