//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.WebshopService.Http;



namespace UnityEngine.Purchasing.WebshopService.Models
{
    /// <summary>
    /// WebshopLinkParam model
    /// </summary>
    [Preserve]
    [DataContract(Name = "WebshopLinkParam")]
    internal class WebshopLinkParam
    {
        /// <summary>
        /// Creates an instance of WebshopLinkParam.
        /// </summary>
        /// <param name="type">The parameter kind; determines the query key and per-type validation.</param>
        /// <param name="value">The parameter value, URL-encoded onto the link.</param>
        [Preserve]
        public WebshopLinkParam(TypeOptions type, string value)
        {
            Type = type;
            Value = value;
        }

        /// <summary>
        /// The parameter kind; determines the query key and per-type validation.
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeOptions Type{ get; }
        
        /// <summary>
        /// The parameter value, URL-encoded onto the link.
        /// </summary>
        [Preserve]
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value{ get; }
    
        /// <summary>
        /// The parameter kind; determines the query key and per-type validation.
        /// </summary>
        /// <value>The parameter kind; determines the query key and per-type validation.</value>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeOptions
        {
            /// <summary>
            /// Enum SessionToken for value: sessionToken
            /// </summary>
            [EnumMember(Value = "sessionToken")]
            SessionToken = 1,
            /// <summary>
            /// Enum Locale for value: locale
            /// </summary>
            [EnumMember(Value = "locale")]
            Locale = 2,
            /// <summary>
            /// Enum Currency for value: currency
            /// </summary>
            [EnumMember(Value = "currency")]
            Currency = 3,
            /// <summary>
            /// Enum Country for value: country
            /// </summary>
            [EnumMember(Value = "country")]
            Country = 4,
            /// <summary>
            /// Enum CatalogListingId for value: catalogListingId
            /// </summary>
            [EnumMember(Value = "catalogListingId")]
            CatalogListingId = 5,
            /// <summary>
            /// Enum ImpressionId for value: impressionId
            /// </summary>
            [EnumMember(Value = "impressionId")]
            ImpressionId = 6,
            /// <summary>
            /// Enum AppleAcquisition for value: appleAcquisition
            /// </summary>
            [EnumMember(Value = "appleAcquisition")]
            AppleAcquisition = 7,
            /// <summary>
            /// Enum AppleServices for value: appleServices
            /// </summary>
            [EnumMember(Value = "appleServices")]
            AppleServices = 8,
            /// <summary>
            /// Enum AppleLinkOut for value: appleLinkOut
            /// </summary>
            [EnumMember(Value = "appleLinkOut")]
            AppleLinkOut = 9,
            /// <summary>
            /// Enum Google for value: google
            /// </summary>
            [EnumMember(Value = "google")]
            Google = 10
        }

        /// <summary>
        /// Formats a WebshopLinkParam into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            serializedModel += "type," + Type + ",";
            if (Value != null)
            {
                serializedModel += "value," + Value;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a WebshopLinkParam as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            var typeStringValue = Type.ToString();
            dictionary.Add("type", typeStringValue);
            
            if (Value != null)
            {
                var valueStringValue = Value.ToString();
                dictionary.Add("value", valueStringValue);
            }
            
            return dictionary;
        }
    }
}
