#nullable enable
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using UnityEngine.Purchasing.PaymentProviders;

namespace UnityEngine.Purchasing
{
    /// <summary>
    /// A public interface for the Payment Providers purchase service extension.
    /// </summary>
    public interface IPaymentProvidersExtendedPurchaseService : IPurchaseServiceExtension
    {
        /// <summary>
        /// Force the use of a specific payment provider in the purchase flow.
        /// Overrides are case-sensitive.
        /// </summary>
        /// <param name="paymentProviderOverride">`null` by default. If not `null`, the payment provider used for purchases.</param>
        void SetPaymentProviderOverride(string? paymentProviderOverride);

        /// <summary>
        /// Register a developer-supplied compliance check invoked at the start of every
        /// Payment Provider purchase, before Unity creates an order on the backend.
        ///
        /// Use this to gate purchases on business rules Unity cannot know about
        /// (e.g. backend account state, regional terms-of-service acceptance, marketing opt-in).
        /// The callback is awaited, so it can show UI and wait for user input.
        ///
        /// Returning `false` short-circuits the purchase with
        /// <see cref="PurchaseFailureReason.PurchasingUnavailable"/> and no order is created.
        /// Returning `true` lets the purchase proceed normally.
        /// An exception thrown by the callback is treated the same as returning `false`.
        ///
        /// Unity owns the platform notice and redirect on the developer's behalf and does not
        /// expose a notice-type knob: on Apple the notice is shown in
        /// <see cref="ExternalPurchaseNoticeType.Browser"/> mode; on Google Play the external
        /// link is launched as a `LINK_TO_DIGITAL_CONTENT_OFFER` with `CALLER_WILL_LAUNCH_LINK`.
        /// </summary>
        /// <param name="complianceCheck">
        /// The compliance callback.
        /// Pass `null` to clear a previously registered callback (the default behavior treats every purchase as compliant).
        /// </param>
        void SetComplianceCheck(Func<PaymentProviderComplianceContext, Task<bool>>? complianceCheck);

        /// <summary>
        /// Returns the redirect URL the player will be sent to in order to complete the purchase.
        ///
        /// This method is intended for use inside the compliance callback registered with
        /// <see cref="SetComplianceCheck"/>, where the URL must be shown or disclosed to the
        /// player before the purchase is approved.
        /// </summary>
        /// <param name="catalogListingId">The catalog listing id of the offer to create the order for.</param>
        /// <param name="externalTokens">
        /// Reporting tokens forwarded to the Payment Provider backend. Generated by the platform
        /// store implementation before this call: Apple tokens come from
        /// <c>ExternalPurchase.FetchTokenAsync</c> (one per required region type — Acquisition /
        /// Services in the EU, LinkOut in Japan); the Google token comes from
        /// <c>BillingClient.CreateBillingProgramReportingDetailsAsync</c>. Pass <c>null</c> when
        /// no token is required.
        /// </param>
        /// <returns>The redirect URL the player will be sent to in order to complete the purchase.</returns>
        Task<string?> GenerateURL(string? catalogListingId, IReadOnlyList<PaymentProviderToken>? externalTokens = null);

        /// <summary>
        /// Fetches the webshop URL for the given catalog listing (or a generic Unity webshop link
        /// when <paramref name="catalogListingId"/> is null), runs the compliance callback
        /// registered with <see cref="SetComplianceCheck"/> (if any), and opens the URL when
        /// compliance approves. When no catalog listing is provided, the compliance callback
        /// receives an empty cart so developers can still gate access globally. The compliance
        /// callback can call <see cref="GenerateURL"/> to retrieve the webshop URL that is about
        /// to be opened. Network failures from the URL fetch propagate as exceptions on the
        /// returned task; compliance rejection short-circuits the redirect via the standard
        /// <see cref="IPurchaseService.OnPurchaseFailed"/> path.
        /// </summary>
        /// <param name="catalogListingId">The catalog listing id to deep-link into on the webshop, or null to open the generic Unity webshop.</param>
        /// <param name="externalTokens">Optional platform reporting tokens forwarded to the webshop backend.</param>
        Task RedirectToWebshop(string? catalogListingId = null, IReadOnlyList<PaymentProviderToken>? externalTokens = null);

        /// <summary>
        /// Routes a single purchase through a specific payment provider. Equivalent to
        /// <see cref="IPurchaseService.Purchase(ICart)"/> except the supplied
        /// <paramref name="paymentProviderName"/> is used for this call only, without mutating
        /// the value set by <see cref="SetPaymentProviderOverride"/>.
        /// </summary>
        /// <param name="cart">The cart to purchase.</param>
        /// <param name="paymentProviderName">Provider id (e.g. <c>"stripe"</c>, <c>"codapay"</c>). Case-sensitive.</param>
        /// <remarks>A null or empty <paramref name="paymentProviderName"/> is reported via <see cref="IPurchaseService.OnPurchaseFailed"/> with <see cref="PurchaseFailureReason.Unknown"/>; no exception is thrown.</remarks>
        void Purchase(ICart cart, string paymentProviderName);

        /// <summary>
        /// Routes a single purchase for a catalog listing through a specific payment provider.
        /// Equivalent to <see cref="IPurchaseService.PurchaseProduct(string)"/> except the supplied
        /// <paramref name="paymentProviderName"/> is used for this call only, without mutating
        /// the value set by <see cref="SetPaymentProviderOverride"/>.
        /// </summary>
        /// <param name="catalogListingId">The catalog listing id to purchase.</param>
        /// <param name="paymentProviderName">Provider id (e.g. <c>"stripe"</c>, <c>"codapay"</c>). Case-sensitive.</param>
        /// <remarks>A null or empty <paramref name="paymentProviderName"/> is reported via <see cref="IPurchaseService.OnPurchaseFailed"/> with <see cref="PurchaseFailureReason.Unknown"/>; no exception is thrown.</remarks>
        void PurchaseProduct(string catalogListingId, string paymentProviderName);
    }
}
