//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.LiveContentAdapterService.Http;



namespace UnityEngine.Purchasing.LiveContentAdapterService.Models
{
    /// <summary>
    /// ClientFile model
    /// </summary>
    [Preserve]
    [DataContract(Name = "clientFile")]
    internal class ClientFile
    {
        /// <summary>
        /// Creates an instance of ClientFile.
        /// </summary>
        /// <param name="contentHash">Base64-encoded SHA-256 hash of the file content (44 characters in Base64, including padding). MD5 (deprecated) is accepted for legacy compatibility.</param>
        /// <param name="contentSize">contentSize param</param>
        /// <param name="contentType">contentType param</param>
        /// <param name="contentUri">contentUri param</param>
        /// <param name="id">id param</param>
        /// <param name="path">path param</param>
        /// <param name="type">type param</param>
        /// <param name="variantTag">variantTag param</param>
        [Preserve]
        public ClientFile(string contentHash = default, long contentSize = default, string contentType = default, string contentUri = default, string id = default, string path = default, ResourceType type = default, List<string> variantTag = default)
        {
            ContentHash = contentHash;
            ContentSize = contentSize;
            ContentType = contentType;
            ContentUri = contentUri;
            Id = id;
            Path = path;
            Type = type;
            VariantTag = variantTag;
        }

        /// <summary>
        /// Base64-encoded SHA-256 hash of the file content (44 characters in Base64, including padding). MD5 (deprecated) is accepted for legacy compatibility.
        /// </summary>
        [Preserve]
        [DataMember(Name = "contentHash", EmitDefaultValue = false)]
        public string ContentHash{ get; }
        
        /// <summary>
        /// Parameter contentSize of ClientFile
        /// </summary>
        [Preserve]
        [DataMember(Name = "contentSize", EmitDefaultValue = false)]
        public long ContentSize{ get; }
        
        /// <summary>
        /// Parameter contentType of ClientFile
        /// </summary>
        [Preserve]
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        public string ContentType{ get; }
        
        /// <summary>
        /// Parameter contentUri of ClientFile
        /// </summary>
        [Preserve]
        [DataMember(Name = "contentUri", EmitDefaultValue = false)]
        public string ContentUri{ get; }
        
        /// <summary>
        /// Parameter id of ClientFile
        /// </summary>
        [Preserve]
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id{ get; }
        
        /// <summary>
        /// Parameter path of ClientFile
        /// </summary>
        [Preserve]
        [DataMember(Name = "path", EmitDefaultValue = false)]
        public string Path{ get; }
        
        /// <summary>
        /// Parameter type of ClientFile
        /// </summary>
        [Preserve]
        [JsonConverter(typeof(StringEnumConverter))]
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public ResourceType Type{ get; }
        
        /// <summary>
        /// Parameter variantTag of ClientFile
        /// </summary>
        [Preserve]
        [DataMember(Name = "variantTag", EmitDefaultValue = false)]
        public List<string> VariantTag{ get; }
    
        /// <summary>
        /// Formats a ClientFile into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (ContentHash != null)
            {
                serializedModel += "contentHash," + ContentHash + ",";
            }
            serializedModel += "contentSize," + ContentSize.ToString() + ",";
            if (ContentType != null)
            {
                serializedModel += "contentType," + ContentType + ",";
            }
            if (ContentUri != null)
            {
                serializedModel += "contentUri," + ContentUri + ",";
            }
            if (Id != null)
            {
                serializedModel += "id," + Id + ",";
            }
            if (Path != null)
            {
                serializedModel += "path," + Path + ",";
            }
            serializedModel += "type," + Type.ToString() + ",";
            if (VariantTag != null)
            {
                serializedModel += "variantTag," + VariantTag.ToString();
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a ClientFile as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (ContentHash != null)
            {
                var contentHashStringValue = ContentHash.ToString();
                dictionary.Add("contentHash", contentHashStringValue);
            }
            
            var contentSizeStringValue = ContentSize.ToString();
            dictionary.Add("contentSize", contentSizeStringValue);
            
            if (ContentType != null)
            {
                var contentTypeStringValue = ContentType.ToString();
                dictionary.Add("contentType", contentTypeStringValue);
            }
            
            if (ContentUri != null)
            {
                var contentUriStringValue = ContentUri.ToString();
                dictionary.Add("contentUri", contentUriStringValue);
            }
            
            if (Id != null)
            {
                var idStringValue = Id.ToString();
                dictionary.Add("id", idStringValue);
            }
            
            if (Path != null)
            {
                var pathStringValue = Path.ToString();
                dictionary.Add("path", pathStringValue);
            }
            
            var typeStringValue = Type.ToString();
            dictionary.Add("type", typeStringValue);
            
            if (VariantTag != null)
            {
                var variantTagStringValue = VariantTag.ToString();
                dictionary.Add("variantTag", variantTagStringValue);
            }
            
            return dictionary;
        }
    }
}
