//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;

namespace UnityEngine.Purchasing.TransactionVerifier.Models
{
    /// <summary>
    /// Interface to a result that could be one of many possible types.
    /// </summary>
    internal interface IOneOf
    {
        /// <summary>The type of the value.</summary>
        Type Type { get; }
        /// <summary>The value.</summary>
        object Value { get; }
    }
}
