//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using UnityEngine.Purchasing.TransactionVerifier.Http;



namespace UnityEngine.Purchasing.TransactionVerifier.Models
{
    /// <summary>
    /// VerifyAppleTransactionRequest model
    /// </summary>
    [Preserve]
    [DataContract(Name = "verify-apple-transaction-request")]
    internal class VerifyAppleTransactionRequest
    {
        /// <summary>
        /// Creates an instance of VerifyAppleTransactionRequest.
        /// </summary>
        /// <param name="jwsTransaction">JWS string of the Apple App Store transaction</param>
        [Preserve]
        public VerifyAppleTransactionRequest(string jwsTransaction)
        {
            JwsTransaction = jwsTransaction;
        }

        /// <summary>
        /// JWS string of the Apple App Store transaction
        /// </summary>
        [Preserve]
        [DataMember(Name = "jwsTransaction", IsRequired = true, EmitDefaultValue = true)]
        public string JwsTransaction{ get; }

        /// <summary>
        /// Formats a VerifyAppleTransactionRequest into a string of key-value pairs for use as a path parameter.
        /// </summary>
        /// <returns>Returns a string representation of the key-value pairs.</returns>
        internal string SerializeAsPathParam()
        {
            var serializedModel = "";

            if (JwsTransaction != null)
            {
                serializedModel += "jwsTransaction," + JwsTransaction;
            }
            return serializedModel;
        }

        /// <summary>
        /// Returns a VerifyAppleTransactionRequest as a dictionary of key-value pairs for use as a query parameter.
        /// </summary>
        /// <returns>Returns a dictionary of string key-value pairs.</returns>
        internal Dictionary<string, string> GetAsQueryParam()
        {
            var dictionary = new Dictionary<string, string>();

            if (JwsTransaction != null)
            {
                var jwsTransactionStringValue = JwsTransaction.ToString();
                dictionary.Add("jwsTransaction", jwsTransactionStringValue);
            }

            return dictionary;
        }
    }
}
