#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

namespace Unity.Purchasing.Editor.Shared.WebApi
{
    /// <summary>
    /// API Exception
    /// </summary>
    public enum ApiErrorType
    {
        /// <summary>
        /// No error
        /// </summary>
        None,

        /// <summary>
        /// Operation Canceled
        /// </summary>
        Canceled,

        /// <summary>
        /// Invalid Parameters
        /// </summary>
        InvalidParameters,

        /// <summary>
        /// Network exception (status code 5XX)
        /// </summary>
        Network,

        /// <summary>
        /// Http exception (status code 4XX)
        /// </summary>
        Http,

        /// <summary>
        /// Exception when trying to deserialize response
        /// </summary>
        Deserialization
    }
}
#endif
