#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Unity.Purchasing.Editor.Shared.WebApi
{
    /// <summary>
    /// Class for encapsulating generic json types as a JToken.
    /// </summary>
    class ApiObjectConverter : JsonConverter
    {
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var apiObject = (ApiObject)value;
            apiObject.Token.WriteTo(writer);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            return new ApiObject(JToken.Load(reader));
        }

        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }
}
#endif