#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS
//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System.Threading;

namespace Unity.Purchasing.Editor.Shared.WebApi
{
    /// <summary>
    /// Contract for Asynchronous RESTful API interactions.
    ///
    /// This interface allows consumers to provide a custom API accessor client.
    /// </summary>
    public interface IApiClient
    {
        /// <summary>
        /// Executes a call to <paramref name="path"/> using the GET http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Get(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the GET http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Get<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the POST http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Post(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the POST http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Post<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the PUT http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Put(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the PUT http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Put<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the DELETE http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Delete(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the DELETE http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Delete<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the HEAD http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Head(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the HEAD http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Head<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the OPTIONS http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Options(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the OPTIONS http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Options<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the PATCH http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation Patch(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);

        /// <summary>
        /// Executes a call to <paramref name="path"/> using the PATCH http verb.
        /// </summary>
        /// <param name="path">The relative path to invoke.</param>
        /// <param name="options">The request parameters to pass along to the client.</param>
        /// <param name="configuration">Per-request configurable settings.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <typeparam name="T">The return type.</typeparam>
        /// <returns>The operation</returns>
        ApiOperation<T> Patch<T>(string path, ApiRequestOptions options, IApiConfiguration configuration, CancellationToken cancellationToken = default);
    }
}
#endif
