//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System.Threading.Tasks;
using System.Collections.Generic;
using UnityEngine.Purchasing.TransactionVerifier.Models;
using UnityEngine.Purchasing.TransactionVerifier.Http;
using Unity.Services.Authentication.Internal;
using UnityEngine.Purchasing.TransactionVerifier.Apple;

namespace UnityEngine.Purchasing.TransactionVerifier.Apis.Apple
{
    /// <summary>
    /// Interface for the AppleApiClient
    /// </summary>
    internal interface IAppleApiClient
    {
            /// <summary>
            /// Async Operation.
            /// Mark an Apple App Store transaction as fulfilled.
            /// </summary>
            /// <param name="request">Request object for FulfillAppleTransaction.</param>
            /// <param name="operationConfiguration">Configuration for FulfillAppleTransaction.</param>
            /// <returns>Task for a Response object containing status code, headers, and GoogleTransactionDto object.</returns>
            /// <exception cref="UnityEngine.Purchasing.TransactionVerifier.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<GoogleTransactionDto>> FulfillAppleTransactionAsync(UnityEngine.Purchasing.TransactionVerifier.Apple.FulfillAppleTransactionRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Mark an Apple App Store transaction as refunded.
            /// </summary>
            /// <param name="request">Request object for RefundAppleTransaction.</param>
            /// <param name="operationConfiguration">Configuration for RefundAppleTransaction.</param>
            /// <returns>Task for a Response object containing status code, headers, and GoogleTransactionDto object.</returns>
            /// <exception cref="UnityEngine.Purchasing.TransactionVerifier.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<GoogleTransactionDto>> RefundAppleTransactionAsync(UnityEngine.Purchasing.TransactionVerifier.Apple.RefundAppleTransactionRequest request, Configuration operationConfiguration = null);

            /// <summary>
            /// Async Operation.
            /// Verify Apple App Store transaction.
            /// </summary>
            /// <param name="request">Request object for VerifyAppleTransaction.</param>
            /// <param name="operationConfiguration">Configuration for VerifyAppleTransaction.</param>
            /// <returns>Task for a Response object containing status code, headers, and AppleTransactionDto object.</returns>
            /// <exception cref="UnityEngine.Purchasing.TransactionVerifier.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
            Task<Response<AppleTransactionDto>> VerifyAppleTransactionAsync(UnityEngine.Purchasing.TransactionVerifier.Apple.VerifyAppleTransactionRequest request, Configuration operationConfiguration = null);

    }

    ///<inheritdoc cref="IAppleApiClient"/>
    internal class AppleApiClient : BaseApiClient, IAppleApiClient
    {
        private IAccessToken _accessToken;
        private const int _baseTimeout = 10;
        private Configuration _configuration;
        /// <summary>
        /// Accessor for the client configuration object. This returns a merge
        /// between the current configuration and the global configuration to
        /// ensure the correct combination of headers and a base path (if it is
        /// set) are returned.
        /// </summary>
        public Configuration Configuration
        {
            get {
                // We return a merge between the current configuration and the
                // global configuration to ensure we have the correct
                // combination of headers and a base path (if it is set).
                Configuration globalConfiguration = new Configuration("https://transaction-verifier.services.api.unity.com", 10, 4, null);
                if (TransactionVerifierService.Instance != null)
                {
                    globalConfiguration = TransactionVerifierService.Instance.Configuration;
                }
                return Configuration.MergeConfigurations(_configuration, globalConfiguration);
            }
            set { _configuration = value; }
        }

        /// <summary>
        /// AppleApiClient Constructor.
        /// </summary>
        /// <param name="httpClient">The HttpClient for AppleApiClient.</param>
        /// <param name="accessToken">The Authentication token for the client.</param>
        /// <param name="configuration"> AppleApiClient Configuration object.</param>
        public AppleApiClient(IHttpClient httpClient,
            IAccessToken accessToken,
            Configuration configuration = null) : base(httpClient)
        {
            // We don't need to worry about the configuration being null at
            // this stage, we will check this in the accessor.
            _configuration = configuration;

            _accessToken = accessToken;
        }


        /// <summary>
        /// Async Operation.
        /// Mark an Apple App Store transaction as fulfilled.
        /// </summary>
        /// <param name="request">Request object for FulfillAppleTransaction.</param>
        /// <param name="operationConfiguration">Configuration for FulfillAppleTransaction.</param>
        /// <returns>Task for a Response object containing status code, headers, and GoogleTransactionDto object.</returns>
        /// <exception cref="UnityEngine.Purchasing.TransactionVerifier.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<GoogleTransactionDto>> FulfillAppleTransactionAsync(UnityEngine.Purchasing.TransactionVerifier.Apple.FulfillAppleTransactionRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(GoogleTransactionDto)   },{"401", typeof(BasicErrorResponse)   },{"403", typeof(BasicErrorResponse)   },{"404", typeof(BasicErrorResponse)   },{"409", typeof(BasicErrorResponse)   },{"429", typeof(BasicErrorResponse)   },{"500", typeof(BasicErrorResponse)   },{"503", typeof(BasicErrorResponse)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<GoogleTransactionDto>(response, statusCodeToTypeMap);
            return new Response<GoogleTransactionDto>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Mark an Apple App Store transaction as refunded.
        /// </summary>
        /// <param name="request">Request object for RefundAppleTransaction.</param>
        /// <param name="operationConfiguration">Configuration for RefundAppleTransaction.</param>
        /// <returns>Task for a Response object containing status code, headers, and GoogleTransactionDto object.</returns>
        /// <exception cref="UnityEngine.Purchasing.TransactionVerifier.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<GoogleTransactionDto>> RefundAppleTransactionAsync(UnityEngine.Purchasing.TransactionVerifier.Apple.RefundAppleTransactionRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(GoogleTransactionDto)   },{"401", typeof(BasicErrorResponse)   },{"403", typeof(BasicErrorResponse)   },{"404", typeof(BasicErrorResponse)   },{"409", typeof(BasicErrorResponse)   },{"429", typeof(BasicErrorResponse)   },{"500", typeof(BasicErrorResponse)   },{"503", typeof(BasicErrorResponse)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<GoogleTransactionDto>(response, statusCodeToTypeMap);
            return new Response<GoogleTransactionDto>(response, handledResponse);
        }


        /// <summary>
        /// Async Operation.
        /// Verify Apple App Store transaction.
        /// </summary>
        /// <param name="request">Request object for VerifyAppleTransaction.</param>
        /// <param name="operationConfiguration">Configuration for VerifyAppleTransaction.</param>
        /// <returns>Task for a Response object containing status code, headers, and AppleTransactionDto object.</returns>
        /// <exception cref="UnityEngine.Purchasing.TransactionVerifier.Http.HttpException">An exception containing the HttpClientResponse with headers, response code, and string of error.</exception>
        public async Task<Response<AppleTransactionDto>> VerifyAppleTransactionAsync(UnityEngine.Purchasing.TransactionVerifier.Apple.VerifyAppleTransactionRequest request,
            Configuration operationConfiguration = null)
        {
            var statusCodeToTypeMap = new Dictionary<string, System.Type>() { {"200", typeof(AppleTransactionDto)   },{"401", typeof(BasicErrorResponse)   },{"403", typeof(BasicErrorResponse)   },{"404", typeof(BasicErrorResponse)   },{"429", typeof(BasicErrorResponse)   },{"500", typeof(BasicErrorResponse)   },{"503", typeof(BasicErrorResponse)   } };

            // Merge the operation/request level configuration with the client level configuration.
            var finalConfiguration = Configuration.MergeConfigurations(operationConfiguration, Configuration);

            var response = await HttpClient.MakeRequestAsync("POST",
                request.ConstructUrl(finalConfiguration.BasePath),
                request.ConstructBody(),
                request.ConstructHeaders(_accessToken, finalConfiguration),
                finalConfiguration.RequestTimeout ?? _baseTimeout);

            var handledResponse = ResponseHandler.HandleAsyncResponse<AppleTransactionDto>(response, statusCodeToTypeMap);
            return new Response<AppleTransactionDto>(response, handledResponse);
        }

    }
}
