#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS

//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IFilesApi : IApiAccessor
    {
        /// <summary>
        /// Update multiple files
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreateBatch">Array of files to update</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<BatchUpdateResponse> UpdateFiles(string environmentId, string projectId, List<FileCreateBatch> fileCreateBatch, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default);

        /// <summary>
        /// Create multiple files
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreateBatch">Array of files to create</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<BatchCreateResponse> CreateFiles(string environmentId, string projectId, List<FileCreateBatch> fileCreateBatch, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete multiple files
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileDeleteBatch">Array of files to delete</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<BatchDeleteResponse> DeleteFiles(string environmentId, string projectId, List<FileDeleteBatch> fileDeleteBatch, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default);

        /// <summary>
        /// Get file content
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation GetFileContent(string environmentId, string filePath, string projectId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default);

        /// <summary>
        /// Get files
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="page">Current Page (optional)</param>
        /// <param name="after">Path-based cursor - returns files listed after this cursor token. Use X-Next-Cursor from the previous response. (optional)</param>
        /// <param name="start">Path-based cursor - Start from the first file. Use with sortBy to control ordering. (optional)</param>
        /// <param name="limit">Items Per Page (optional, default to 10)</param>
        /// <param name="path">Path (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="noVariantTag">Deprecated: use &#x60;variantTag&#x3D;&#x60; (empty value) instead. When true, returns only files that have no variant tags assigned, ignoring the variantTag parameter. When false or omitted, this filter is not applied. (optional) (deprecated)</param>
        /// <param name="contentType">content type (optional)</param>
        /// <param name="complete">is content upload completed or not (optional)</param>
        /// <param name="sortBy">Sort By (optional)</param>
        /// <param name="sortOrder">Sort Order (optional)</param>
        /// <param name="metadata">AIP-160 filter expression scoped to the metadata object. Field paths are relative to the metadata object — do not include a \&quot;metadata.\&quot; prefix. Supported operators: &#x3D; !&#x3D; &lt; &lt;&#x3D; &gt; &gt;&#x3D; : (has/contains) AND OR NOT. Wildcards: use * in string values for glob matching (e.g. \&quot;io*\&quot; matches \&quot;ios\&quot;). Examples: ?metadata&#x3D;platform&#x3D;\&quot;ios\&quot; ?metadata&#x3D;platform&#x3D;\&quot;ios\&quot; AND version&gt;3 ?metadata&#x3D;platform&#x3D;\&quot;ios\&quot; OR platform&#x3D;\&quot;android\&quot; ?metadata&#x3D;NOT platform&#x3D;\&quot;web\&quot; ?metadata&#x3D;tags:\&quot;mobile\&quot; ?metadata&#x3D;version:* (optional)</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<List<FileMetadata>> GetFiles(string environmentId, string projectId, long? page = default(long?), string after = default(string), bool? start = default(bool?), long? limit = default(long?), string path = default(string), List<string> variantTag = default(List<string>), bool? noVariantTag = default(bool?), string contentType = default(string), bool? complete = default(bool?), SortBy? sortBy = default(SortBy?), SortOrder? sortOrder = default(SortOrder?), string metadata = default(string), string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete all files
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation DeleteAllFiles(string projectId, string environmentId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default);

        /// <summary>
        /// Get file
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<FileMetadata> GetFile(string environmentId, string filePath, string projectId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default);

        /// <summary>
        /// Update file
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreate">File</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<FileMetadata> UpdateFile(string environmentId, string filePath, string projectId, FileCreate fileCreate, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default);

        /// <summary>
        /// Create file
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreate">File</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<FileMetadata> CreateFile(string environmentId, string filePath, string projectId, FileCreate fileCreate, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete file
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<DeleteConfig200Response> DeleteFile(string environmentId, string filePath, string projectId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default);

        /// <summary>
        /// Partial Update file
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileUpdate">File</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<FileMetadata> PartialUpdateFile(string environmentId, string filePath, string projectId, FileUpdate fileUpdate, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal partial class FilesApi : IFilesApi
    {
        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IApiClient Client { get; }

        /// <summary>
        /// Gets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IApiConfiguration Configuration { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="apiClient">The client interface for synchronous API access.</param>
        public FilesApi(IApiClient apiClient)
        {
            if (apiClient == null) throw new ArgumentNullException("apiClient");

            this.Client = apiClient;
            this.Configuration = new ApiConfiguration() { BasePath = "https://services.api.unity.com/live-content/admin" };
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="apiClient">The client interface for synchronous API access.</param>
        /// <param name="apiConfiguration">The configuration object.</param>
        public FilesApi(IApiClient apiClient, IApiConfiguration apiConfiguration)
        {
            if (apiClient == null) throw new ArgumentNullException("apiClient");
            if (apiConfiguration == null) throw new ArgumentNullException("apiConfiguration");

            this.Client = apiClient;
            this.Configuration = apiConfiguration;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <returns>The base path</returns>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Update multiple files Updates multiple files in a batch operation. All properties are overwritten; omitted fields revert to their defaults.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreateBatch">Array of files to update</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<BatchUpdateResponse> UpdateFiles(string environmentId, string projectId, List<FileCreateBatch> fileCreateBatch, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<BatchUpdateResponse>(new ApiResponse<BatchUpdateResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.UpdateFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<BatchUpdateResponse>(new ApiResponse<BatchUpdateResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.UpdateFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fileCreateBatch == null)
            {
                return new ApiOperation<BatchUpdateResponse>(new ApiResponse<BatchUpdateResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'fileCreateBatch' when calling FilesApi.UpdateFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { "application/json" };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Data = fileCreateBatch;

            apiRequestOptions.Operation = "FilesApi.UpdateFiles";

            return this.Client.Put<BatchUpdateResponse>("/v1/projects/{projectId}/environments/{environmentId}/files/batch/info", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Create multiple files Creates multiple new files information in a batch operation.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreateBatch">Array of files to create</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<BatchCreateResponse> CreateFiles(string environmentId, string projectId, List<FileCreateBatch> fileCreateBatch, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<BatchCreateResponse>(new ApiResponse<BatchCreateResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.CreateFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<BatchCreateResponse>(new ApiResponse<BatchCreateResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.CreateFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fileCreateBatch == null)
            {
                return new ApiOperation<BatchCreateResponse>(new ApiResponse<BatchCreateResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'fileCreateBatch' when calling FilesApi.CreateFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { "application/json" };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Data = fileCreateBatch;

            apiRequestOptions.Operation = "FilesApi.CreateFiles";

            return this.Client.Post<BatchCreateResponse>("/v1/projects/{projectId}/environments/{environmentId}/files/batch/info", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Delete multiple files Delete multiple files information in a batch operation.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileDeleteBatch">Array of files to delete</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<BatchDeleteResponse> DeleteFiles(string environmentId, string projectId, List<FileDeleteBatch> fileDeleteBatch, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<BatchDeleteResponse>(new ApiResponse<BatchDeleteResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.DeleteFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<BatchDeleteResponse>(new ApiResponse<BatchDeleteResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.DeleteFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fileDeleteBatch == null)
            {
                return new ApiOperation<BatchDeleteResponse>(new ApiResponse<BatchDeleteResponse>() { StatusCode = -1, ErrorText = "Missing required parameter 'fileDeleteBatch' when calling FilesApi.DeleteFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { "application/json" };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Data = fileDeleteBatch;

            apiRequestOptions.Operation = "FilesApi.DeleteFiles";

            return this.Client.Delete<BatchDeleteResponse>("/v1/projects/{projectId}/environments/{environmentId}/files/batch/info", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Get file content Retrieve the content of a single file.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation GetFileContent(string environmentId, string filePath, string projectId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation(new ApiResponse() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.GetFileContent", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (filePath == null)
            {
                return new ApiOperation(new ApiResponse() { StatusCode = -1, ErrorText = "Missing required parameter 'filePath' when calling FilesApi.GetFileContent", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation(new ApiResponse() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.GetFileContent", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("filePath", ApiUtils.ParameterToString(Configuration, filePath));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Operation = "FilesApi.GetFileContent";

            return this.Client.Get("/v1/projects/{projectId}/environments/{environmentId}/files/content/{filePath}", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Get files Gets all files information for a given environment. Files can be searched/queried by path or variant tag. For example, to search by path you can do \&quot;/files/info?path&#x3D;asset.bundle\&quot;. To search by variant tag you can do \&quot;/files/info?variantTag&#x3D;android\&quot;. To search for files with no variant tags, use \&quot;/files/info?variantTag\&quot;. To get all files regardless of variant tags, use \&quot;/files/info\&quot; (omit the variantTag parameter).
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="page">Current Page (optional)</param>
        /// <param name="after">Path-based cursor - returns files listed after this cursor token. Use X-Next-Cursor from the previous response. (optional)</param>
        /// <param name="start">Path-based cursor - Start from the first file. Use with sortBy to control ordering. (optional)</param>
        /// <param name="limit">Items Per Page (optional, default to 10)</param>
        /// <param name="path">Path (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="noVariantTag">Deprecated: use &#x60;variantTag&#x3D;&#x60; (empty value) instead. When true, returns only files that have no variant tags assigned, ignoring the variantTag parameter. When false or omitted, this filter is not applied. (optional) (deprecated)</param>
        /// <param name="contentType">content type (optional)</param>
        /// <param name="complete">is content upload completed or not (optional)</param>
        /// <param name="sortBy">Sort By (optional)</param>
        /// <param name="sortOrder">Sort Order (optional)</param>
        /// <param name="metadata">AIP-160 filter expression scoped to the metadata object. Field paths are relative to the metadata object — do not include a \&quot;metadata.\&quot; prefix. Supported operators: &#x3D; !&#x3D; &lt; &lt;&#x3D; &gt; &gt;&#x3D; : (has/contains) AND OR NOT. Wildcards: use * in string values for glob matching (e.g. \&quot;io*\&quot; matches \&quot;ios\&quot;). Examples: ?metadata&#x3D;platform&#x3D;\&quot;ios\&quot; ?metadata&#x3D;platform&#x3D;\&quot;ios\&quot; AND version&gt;3 ?metadata&#x3D;platform&#x3D;\&quot;ios\&quot; OR platform&#x3D;\&quot;android\&quot; ?metadata&#x3D;NOT platform&#x3D;\&quot;web\&quot; ?metadata&#x3D;tags:\&quot;mobile\&quot; ?metadata&#x3D;version:* (optional)</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<List<FileMetadata>> GetFiles(string environmentId, string projectId, long? page = default(long?), string after = default(string), bool? start = default(bool?), long? limit = default(long?), string path = default(string), List<string> variantTag = default(List<string>), bool? noVariantTag = default(bool?), string contentType = default(string), bool? complete = default(bool?), SortBy? sortBy = default(SortBy?), SortOrder? sortOrder = default(SortOrder?), string metadata = default(string), string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<List<FileMetadata>>(new ApiResponse<List<FileMetadata>>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.GetFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<List<FileMetadata>>(new ApiResponse<List<FileMetadata>>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.GetFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (page != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "page", page));
            }

            if (after != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "after", after));
            }

            if (start != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "start", start));
            }

            if (limit != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "limit", limit));
            }

            if (path != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "path", path));
            }

            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (noVariantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "noVariantTag", noVariantTag));
            }

            if (contentType != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "contentType", contentType));
            }

            if (complete != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "complete", complete));
            }

            if (sortBy != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "sortBy", sortBy));
            }

            if (sortOrder != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "sortOrder", sortOrder));
            }

            if (metadata != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "metadata", metadata));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Operation = "FilesApi.GetFiles";

            return this.Client.Get<List<FileMetadata>>("/v1/projects/{projectId}/environments/{environmentId}/files/info", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Delete all files Marks all files as deleted within a specific project and environment. All previous versions of files will still exist. No file content is removed.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation DeleteAllFiles(string projectId, string environmentId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation(new ApiResponse() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.DeleteAllFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (environmentId == null)
            {
                return new ApiOperation(new ApiResponse() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.DeleteAllFiles", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Operation = "FilesApi.DeleteAllFiles";

            return this.Client.Delete("/v1/projects/{projectId}/environments/{environmentId}/files/info", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Get file Gets a single file information.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<FileMetadata> GetFile(string environmentId, string filePath, string projectId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.GetFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (filePath == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'filePath' when calling FilesApi.GetFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.GetFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("filePath", ApiUtils.ParameterToString(Configuration, filePath));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Operation = "FilesApi.GetFile";

            return this.Client.Get<FileMetadata>("/v1/projects/{projectId}/environments/{environmentId}/files/info/{filePath}", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Update file Updates an existing file. All properties are overwritten; omitted fields revert to their defaults.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreate">File</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<FileMetadata> UpdateFile(string environmentId, string filePath, string projectId, FileCreate fileCreate, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.UpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (filePath == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'filePath' when calling FilesApi.UpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.UpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fileCreate == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'fileCreate' when calling FilesApi.UpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { "application/json" };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("filePath", ApiUtils.ParameterToString(Configuration, filePath));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Data = fileCreate;

            apiRequestOptions.Operation = "FilesApi.UpdateFile";

            return this.Client.Put<FileMetadata>("/v1/projects/{projectId}/environments/{environmentId}/files/info/{filePath}", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Create file Creates a new file information.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileCreate">File</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<FileMetadata> CreateFile(string environmentId, string filePath, string projectId, FileCreate fileCreate, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.CreateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (filePath == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'filePath' when calling FilesApi.CreateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.CreateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fileCreate == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'fileCreate' when calling FilesApi.CreateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { "application/json" };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("filePath", ApiUtils.ParameterToString(Configuration, filePath));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Data = fileCreate;

            apiRequestOptions.Operation = "FilesApi.CreateFile";

            return this.Client.Post<FileMetadata>("/v1/projects/{projectId}/environments/{environmentId}/files/info/{filePath}", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Delete file Removes a single file information. When DELETE is called on an file we just mark it as deleted but all previous versions of the file still exist. No file content is removed.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<DeleteConfig200Response> DeleteFile(string environmentId, string filePath, string projectId, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<DeleteConfig200Response>(new ApiResponse<DeleteConfig200Response>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.DeleteFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (filePath == null)
            {
                return new ApiOperation<DeleteConfig200Response>(new ApiResponse<DeleteConfig200Response>() { StatusCode = -1, ErrorText = "Missing required parameter 'filePath' when calling FilesApi.DeleteFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<DeleteConfig200Response>(new ApiResponse<DeleteConfig200Response>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.DeleteFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("filePath", ApiUtils.ParameterToString(Configuration, filePath));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Operation = "FilesApi.DeleteFile";

            return this.Client.Delete<DeleteConfig200Response>("/v1/projects/{projectId}/environments/{environmentId}/files/info/{filePath}", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Partial Update file Partially updates a single file&#39;s information.
        /// </summary>
        /// <param name="environmentId">Environment ID</param>
        /// <param name="filePath">File Path</param>
        /// <param name="projectId">Project ID</param>
        /// <param name="fileUpdate">File</param>
        /// <param name="unityLiveReleaseName"> (optional)</param>
        /// <param name="unityLiveReleaseId"> (optional)</param>
        /// <param name="variantTag">Variant Tag. When present, filters results to those with the specified variant tags. Pass one or more values (e.g. &#x60;variantTag&#x3D;ios&amp;variantTag&#x3D;android&#x60;) to match a specific tag set. Pass an empty value (&#x60;variantTag&#x3D;&#x60;) to return only resources that have no variant tags assigned. Omit the parameter entirely to return all resources regardless of variant tags. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<FileMetadata> PartialUpdateFile(string environmentId, string filePath, string projectId, FileUpdate fileUpdate, string unityLiveReleaseName = default(string), string unityLiveReleaseId = default(string), List<string> variantTag = default(List<string>), CancellationToken cancellationToken = default)
        {
            if (environmentId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'environmentId' when calling FilesApi.PartialUpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (filePath == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'filePath' when calling FilesApi.PartialUpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (projectId == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling FilesApi.PartialUpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fileUpdate == null)
            {
                return new ApiOperation<FileMetadata>(new ApiResponse<FileMetadata>() { StatusCode = -1, ErrorText = "Missing required parameter 'fileUpdate' when calling FilesApi.PartialUpdateFile", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { "application/json" };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("environmentId", ApiUtils.ParameterToString(Configuration, environmentId));
            apiRequestOptions.PathParameters.Add("filePath", ApiUtils.ParameterToString(Configuration, filePath));
            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            if (variantTag != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "multi", "variantTag", variantTag));
            }

            if (unityLiveReleaseName != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-name", ApiUtils.ParameterToString(Configuration, unityLiveReleaseName));
            }

            if (unityLiveReleaseId != null)
            {
                apiRequestOptions.HeaderParameters.Add("unity-live-release-id", ApiUtils.ParameterToString(Configuration, unityLiveReleaseId));
            }

            apiRequestOptions.Data = fileUpdate;

            apiRequestOptions.Operation = "FilesApi.PartialUpdateFile";

            return this.Client.Patch<FileMetadata>("/v1/projects/{projectId}/environments/{environmentId}/files/info/{filePath}", apiRequestOptions, this.Configuration, cancellationToken);
        }
    }
}
#endif
