#if UNITY_EDITOR || ENABLE_RUNTIME_ADMIN_APIS

//-----------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Unity.Purchasing.Editor.Shared.WebApi;

namespace UnityEditor.Purchasing.Editor.Authoring.LiveContentAdminApi
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal interface IReleasesApi : IApiAccessor
    {
        /// <summary>
        /// Compare releases diff summary
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="fromReleaseId">Release ID to compare from (release A)</param>
        /// <param name="toReleaseId">Release ID to compare to (release B)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<ReleaseCompareSummary> CompareReleasesDiff(string projectId, string fromReleaseId, string toReleaseId, CancellationToken cancellationToken = default);

        /// <summary>
        /// Compare releases diff assets
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="fromReleaseId">Release ID to compare from (release A)</param>
        /// <param name="toReleaseId">Release ID to compare to (release B)</param>
        /// <param name="page">Current Page (optional)</param>
        /// <param name="limit">Items Per Page (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        ApiOperation<List<FileWithState>> CompareReleasesDiffAssets(string projectId, string fromReleaseId, string toReleaseId, long? page = default(long?), long? limit = default(long?), CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    internal partial class ReleasesApi : IReleasesApi
    {
        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IApiClient Client { get; }

        /// <summary>
        /// Gets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IApiConfiguration Configuration { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleasesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="apiClient">The client interface for synchronous API access.</param>
        public ReleasesApi(IApiClient apiClient)
        {
            if (apiClient == null) throw new ArgumentNullException("apiClient");

            this.Client = apiClient;
            this.Configuration = new ApiConfiguration() { BasePath = "https://services.api.unity.com/live-content/admin" };
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReleasesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="apiClient">The client interface for synchronous API access.</param>
        /// <param name="apiConfiguration">The configuration object.</param>
        public ReleasesApi(IApiClient apiClient, IApiConfiguration apiConfiguration)
        {
            if (apiClient == null) throw new ArgumentNullException("apiClient");
            if (apiConfiguration == null) throw new ArgumentNullException("apiConfiguration");

            this.Client = apiClient;
            this.Configuration = apiConfiguration;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <returns>The base path</returns>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Compare releases diff summary Returns a summary of differences between two releases (added, deleted, modified, unchanged counts).
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="fromReleaseId">Release ID to compare from (release A)</param>
        /// <param name="toReleaseId">Release ID to compare to (release B)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<ReleaseCompareSummary> CompareReleasesDiff(string projectId, string fromReleaseId, string toReleaseId, CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<ReleaseCompareSummary>(new ApiResponse<ReleaseCompareSummary>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling ReleasesApi.CompareReleasesDiff", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fromReleaseId == null)
            {
                return new ApiOperation<ReleaseCompareSummary>(new ApiResponse<ReleaseCompareSummary>() { StatusCode = -1, ErrorText = "Missing required parameter 'fromReleaseId' when calling ReleasesApi.CompareReleasesDiff", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (toReleaseId == null)
            {
                return new ApiOperation<ReleaseCompareSummary>(new ApiResponse<ReleaseCompareSummary>() { StatusCode = -1, ErrorText = "Missing required parameter 'toReleaseId' when calling ReleasesApi.CompareReleasesDiff", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("fromReleaseId", ApiUtils.ParameterToString(Configuration, fromReleaseId));
            apiRequestOptions.PathParameters.Add("toReleaseId", ApiUtils.ParameterToString(Configuration, toReleaseId));

            apiRequestOptions.Operation = "ReleasesApi.CompareReleasesDiff";

            return this.Client.Get<ReleaseCompareSummary>("/v1/projects/{projectId}/releases/{fromReleaseId}/diff/{toReleaseId}", apiRequestOptions, this.Configuration, cancellationToken);
        }

        /// <summary>
        /// Compare releases diff assets Returns per-file differences between two releases with pagination.
        /// </summary>
        /// <param name="projectId">Project ID</param>
        /// <param name="fromReleaseId">Release ID to compare from (release A)</param>
        /// <param name="toReleaseId">Release ID to compare to (release B)</param>
        /// <param name="page">Current Page (optional)</param>
        /// <param name="limit">Items Per Page (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>The operation</returns>
        public ApiOperation<List<FileWithState>> CompareReleasesDiffAssets(string projectId, string fromReleaseId, string toReleaseId, long? page = default(long?), long? limit = default(long?), CancellationToken cancellationToken = default)
        {
            if (projectId == null)
            {
                return new ApiOperation<List<FileWithState>>(new ApiResponse<List<FileWithState>>() { StatusCode = -1, ErrorText = "Missing required parameter 'projectId' when calling ReleasesApi.CompareReleasesDiffAssets", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (fromReleaseId == null)
            {
                return new ApiOperation<List<FileWithState>>(new ApiResponse<List<FileWithState>>() { StatusCode = -1, ErrorText = "Missing required parameter 'fromReleaseId' when calling ReleasesApi.CompareReleasesDiffAssets", ErrorType = ApiErrorType.InvalidParameters });
            }

            if (toReleaseId == null)
            {
                return new ApiOperation<List<FileWithState>>(new ApiResponse<List<FileWithState>>() { StatusCode = -1, ErrorText = "Missing required parameter 'toReleaseId' when calling ReleasesApi.CompareReleasesDiffAssets", ErrorType = ApiErrorType.InvalidParameters });
            }

            ApiRequestOptions apiRequestOptions = new ApiRequestOptions();

            string[] _contentTypes = new string[] { };

            string[] _accepts = new string[] { "application/json" };

            var localContentType = ApiUtils.SelectHeaderContentType(_contentTypes);
            if (localContentType != null)
            {
                apiRequestOptions.HeaderParameters.Add("Content-Type", localContentType);
            }

            var localAccept = ApiUtils.SelectHeaderAccept(_accepts);
            if (localAccept != null)
            {
                apiRequestOptions.HeaderParameters.Add("Accept", localAccept);
            }

            apiRequestOptions.PathParameters.Add("projectId", ApiUtils.ParameterToString(Configuration, projectId));
            apiRequestOptions.PathParameters.Add("fromReleaseId", ApiUtils.ParameterToString(Configuration, fromReleaseId));
            apiRequestOptions.PathParameters.Add("toReleaseId", ApiUtils.ParameterToString(Configuration, toReleaseId));
            if (page != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "page", page));
            }

            if (limit != null)
            {
                apiRequestOptions.QueryParameters.Add(ApiUtils.ParameterToMultiMap(Configuration, "", "limit", limit));
            }

            apiRequestOptions.Operation = "ReleasesApi.CompareReleasesDiffAssets";

            return this.Client.Get<List<FileWithState>>("/v1/projects/{projectId}/releases/{fromReleaseId}/diff/{toReleaseId}/assets", apiRequestOptions, this.Configuration, cancellationToken);
        }
    }
}
#endif
